// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

using System;
using System.Collections.Generic;
using System.Linq;

namespace DeskCallAssistant
{
    public sealed class AnswerConfig
    {
        private readonly string[] _processNames;

        private readonly string[] _buttonLabels;

        public string[] ProcessNames
        {
            get { return _processNames; }
        }

        public string[] ButtonLabels
        {
            get { return _buttonLabels; }
        }

        public AnswerConfig(IEnumerable<string> processNames, IEnumerable<string> buttonLabels)
        {
            _processNames = Normalize(processNames);
            _buttonLabels = Normalize(buttonLabels);
        }

        private static string[] Normalize(IEnumerable<string> rawValues)
        {
            return rawValues
                .Where(value => !string.IsNullOrWhiteSpace(value))
                .Select(value => value.Trim())
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToArray();
        }
    }
}
