// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

using System;

namespace DeskCallAssistant
{
    public static class AppPolicy
    {
        public const bool AllowInternetLearning = false;

        public const bool AllowInternetPublishing = false;

        public const bool LocalOnlyLearning = true;

        public static void EnsureLocalOnlyLearning()
        {
            if (!LocalOnlyLearning || AllowInternetLearning)
            {
                throw new InvalidOperationException("This app is locked to local-only learning.");
            }
        }

        public static string BuildPrivacySummary(string storagePath)
        {
            return string.Format(
                "Privacy policy:{0}- Local-only learning is enforced in code.{0}- Internet learning is disabled.{0}- Internet publishing is disabled.{0}- Local learning data path: {1}",
                Environment.NewLine,
                storagePath);
        }
    }
}
