// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

namespace DeskCallAssistant
{
    public sealed class AppSettings
    {
        public AppSettings()
        {
            AutoDetectReplyLanguage = true;
        }

        public bool AutoAnswerEnabled { get; set; }

        public decimal ScanIntervalSeconds { get; set; }

        public string ProcessNamesText { get; set; }

        public string ButtonLabelsText { get; set; }

        public bool PreferGpu { get; set; }

        public bool StartWithWindows { get; set; }

        public bool MinimizeToTray { get; set; }

        public bool ManualTalkEnabled { get; set; }

        public string VoiceName { get; set; }

        public int VoiceRate { get; set; }

        public int VoiceVolume { get; set; }

        public string SpeechText { get; set; }

        public bool ReplyAssistantEnabled { get; set; }

        public bool AutoSendReplyEnabled { get; set; }

        public bool OpenFiverrOnAssistantStarts { get; set; }

        public decimal ReplyIntervalSeconds { get; set; }

        public string ReplyPlatformId { get; set; }

        public bool AutoDetectReplyLanguage { get; set; }

        public string ReplyLanguage { get; set; }

        public string IncomingMessageText { get; set; }

        public string GeneratedReplyText { get; set; }

        public string FiverrLanguage { get; set; }

        public string FiverrIncomingMessageText { get; set; }

        public string FiverrGeneratedReplyText { get; set; }

        public int WindowWidth { get; set; }

        public int WindowHeight { get; set; }
    }
}
