// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

using System;
using System.IO;
using System.Xml.Serialization;

namespace DeskCallAssistant
{
    public sealed class AppSettingsService
    {
        private readonly string _settingsPath;

        public AppSettingsService()
        {
            var root = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                "DeskCallAssistant");
            Directory.CreateDirectory(root);
            _settingsPath = Path.Combine(root, "AppSettings.xml");
        }

        public string SettingsPath
        {
            get { return _settingsPath; }
        }

        public AppSettings Load()
        {
            try
            {
                if (!File.Exists(_settingsPath))
                {
                    return new AppSettings();
                }

                var serializer = new XmlSerializer(typeof(AppSettings));
                using (var stream = File.OpenRead(_settingsPath))
                {
                    var settings = serializer.Deserialize(stream) as AppSettings;
                    return settings ?? new AppSettings();
                }
            }
            catch
            {
                return new AppSettings();
            }
        }

        public void Save(AppSettings settings)
        {
            if (settings == null)
            {
                return;
            }

            var serializer = new XmlSerializer(typeof(AppSettings));
            using (var stream = File.Create(_settingsPath))
            {
                serializer.Serialize(stream, settings);
            }
        }
    }
}
