// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Windows.Automation;

namespace DeskCallAssistant
{
    public sealed class CallAutomationService
    {
        public CallActionResult TryAnswerIncomingCall(AnswerConfig config)
        {
            if (config == null)
            {
                throw new ArgumentNullException("config");
            }

            if (config.ProcessNames.Length == 0 || config.ButtonLabels.Length == 0)
            {
                return new CallActionResult
                {
                    Answered = false,
                    Message = "Add at least one process name and one answer button label."
                };
            }

            var desktop = AutomationElement.RootElement;
            var windows = desktop.FindAll(TreeScope.Children, Condition.TrueCondition);

            foreach (AutomationElement window in windows)
            {
                if (!MatchesProcess(window, config.ProcessNames))
                {
                    continue;
                }

                var button = FindCandidateButton(window, config.ButtonLabels);
                if (button == null)
                {
                    continue;
                }

                if (TryInvoke(button))
                {
                    return new CallActionResult
                    {
                        Answered = true,
                        Message = "Clicked a matching answer button.",
                        TargetWindow = SafeName(window),
                        ButtonName = SafeName(button)
                    };
                }

                return new CallActionResult
                {
                    Answered = false,
                    Message = "Found a possible answer button, but Windows UI Automation could not invoke it.",
                    TargetWindow = SafeName(window),
                    ButtonName = SafeName(button)
                };
            }

            return new CallActionResult
            {
                Answered = false,
                Message = "No matching incoming-call answer button was found in the configured apps."
            };
        }

        public string[] InspectMatchingButtons(AnswerConfig config)
        {
            var results = new List<string>();
            var desktop = AutomationElement.RootElement;
            var windows = desktop.FindAll(TreeScope.Children, Condition.TrueCondition);

            foreach (AutomationElement window in windows)
            {
                if (!MatchesProcess(window, config.ProcessNames))
                {
                    continue;
                }

                var buttons = window.FindAll(
                    TreeScope.Descendants,
                    new OrCondition(
                        new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Button),
                        new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Hyperlink)));

                foreach (AutomationElement button in buttons)
                {
                    var name = SafeName(button);
                    if (string.IsNullOrWhiteSpace(name))
                    {
                        continue;
                    }

                    results.Add(string.Format(
                        "{0} -> {1}",
                        SafeName(window),
                        name));
                }
            }

            return results
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .OrderBy(value => value)
                .ToArray();
        }

        private static AutomationElement FindCandidateButton(AutomationElement window, string[] buttonLabels)
        {
            var candidates = window.FindAll(
                TreeScope.Descendants,
                new OrCondition(
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Button),
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Hyperlink)));

            foreach (AutomationElement candidate in candidates)
            {
                var name = SafeName(candidate);
                if (buttonLabels.Any(label => name.IndexOf(label, StringComparison.OrdinalIgnoreCase) >= 0))
                {
                    return candidate;
                }
            }

            return null;
        }

        private static bool MatchesProcess(AutomationElement window, string[] processNames)
        {
            try
            {
                var processId = window.Current.ProcessId;
                var process = Process.GetProcessById(processId);
                var name = process.ProcessName;
                return processNames.Any(filter => name.Equals(filter, StringComparison.OrdinalIgnoreCase));
            }
            catch
            {
                return false;
            }
        }

        private static bool TryInvoke(AutomationElement element)
        {
            try
            {
                object invokePattern;
                if (element.TryGetCurrentPattern(InvokePattern.Pattern, out invokePattern))
                {
                    ((InvokePattern)invokePattern).Invoke();
                    return true;
                }

                object selectionPattern;
                if (element.TryGetCurrentPattern(SelectionItemPattern.Pattern, out selectionPattern))
                {
                    ((SelectionItemPattern)selectionPattern).Select();
                    return true;
                }

            }
            catch
            {
                return false;
            }

            return false;
        }

        private static string SafeName(AutomationElement element)
        {
            try
            {
                return element.Current.Name ?? string.Empty;
            }
            catch
            {
                return string.Empty;
            }
        }
    }
}
