// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

namespace DeskCallAssistant
{
    public sealed class CallActionResult
    {
        public bool Answered { get; set; }

        public string Message { get; set; }

        public string TargetWindow { get; set; }

        public string ButtonName { get; set; }
    }
}
