// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Management;

namespace DeskCallAssistant
{
    public sealed class ComputePolicyService
    {
        public ComputeStatus GetStatus(bool preferGpuForBotWorkloads)
        {
            var names = GetGpuNames();
            var status = new ComputeStatus();
            status.GpuNames = names;
            status.GpuAvailable = names.Length > 0;
            status.PreferGpuForBotWorkloads = preferGpuForBotWorkloads;
            status.Summary = BuildSummary(status);
            return status;
        }

        private static string[] GetGpuNames()
        {
            var results = new List<string>();

            try
            {
                using (var searcher = new ManagementObjectSearcher("SELECT Name FROM Win32_VideoController"))
                using (var collection = searcher.Get())
                {
                    foreach (ManagementObject item in collection)
                    {
                        var rawName = item["Name"] as string;
                        if (!string.IsNullOrWhiteSpace(rawName))
                        {
                            results.Add(rawName.Trim());
                        }
                    }
                }
            }
            catch
            {
                return new string[0];
            }

            return results
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToArray();
        }

        private static string BuildSummary(ComputeStatus status)
        {
            var detected = status.GpuAvailable
                ? string.Join(", ", status.GpuNames)
                : "No GPU adapters were detected through Windows Management Instrumentation.";

            var policy = status.PreferGpuForBotWorkloads
                ? "GPU preference is enabled for local bot workloads where a GPU-capable backend exists."
                : "GPU preference is disabled, so local bot workloads stay in the default Windows compute path.";

            const string limitation = "Important: the current Messenger/WhatsApp auto-answer flow and Windows Speech synthesis remain CPU or Windows-service managed operations.";

            return string.Format("{0}{1}{1}{2}{1}{1}{3}", detected, Environment.NewLine, policy, limitation);
        }
    }
}
