// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

namespace DeskCallAssistant
{
    public sealed class ComputeStatus
    {
        public string[] GpuNames { get; set; }

        public bool GpuAvailable { get; set; }

        public bool PreferGpuForBotWorkloads { get; set; }

        public string Summary { get; set; }
    }
}
