// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

namespace DeskCallAssistant
{
    public sealed class ConversationSnapshot
    {
        public bool Found { get; set; }

        public string PlatformId { get; set; }

        public string WindowTitle { get; set; }

        public string ProcessName { get; set; }

        public string LatestIncomingMessage { get; set; }

        public bool ComposerFound { get; set; }

        public string DetectionMode { get; set; }

        public string MatchedElementName { get; set; }

        public string DiagnosticInfo { get; set; }

        public string Message { get; set; }
    }
}
