// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

using System;
using System.Diagnostics;
using System.IO;

namespace DeskCallAssistant
{
    public sealed class FiverrAssistantService
    {
        public const string InboxUrl = "https://www.fiverr.com/inbox";

        private readonly MessagingAutomationService _messagingAutomation;
        private readonly StorageLocationService _storageLocations;
        private MessagingReplyLearningService _replyLearning;
        private string _storagePath;

        public FiverrAssistantService(MessagingAutomationService messagingAutomation, StorageLocationService storageLocations)
        {
            _messagingAutomation = messagingAutomation;
            _storageLocations = storageLocations;
            InitializeStorage();
        }

        public string StoragePath
        {
            get { return _storagePath ?? string.Empty; }
        }

        public string StorageStatus
        {
            get { return _storageLocations.BuildStatusMessage(StoragePath); }
        }

        public bool StorageReady
        {
            get { return !string.IsNullOrWhiteSpace(StoragePath) && _replyLearning != null; }
        }

        public string InboxUrlValue
        {
            get { return InboxUrl; }
        }

        public MessagingPlatformDefinition Platform
        {
            get
            {
                return new MessagingPlatformDefinition
                {
                    Id = "fiverr",
                    DisplayName = "Fiverr Inbox",
                    ProcessNames = new[] { "chrome", "msedge" },
                    WindowTitleHints = new[] { "Fiverr", "Inbox" }
                };
            }
        }

        public void InitializeStorage()
        {
            _storagePath = _storageLocations.EnsureAppDataPath("FiverrMemory");
            if (!string.IsNullOrWhiteSpace(_storagePath))
            {
                _replyLearning = new MessagingReplyLearningService(
                    Path.Combine(_storagePath, "FiverrReplyPatterns.tsv"));
            }
        }

        public ConversationSnapshot DetectInboxConversation()
        {
            return _messagingAutomation.DetectConversation(Platform);
        }

        public ReplySuggestionResult SuggestReply(string incomingText, string language)
        {
            if (!StorageReady)
            {
                return new ReplySuggestionResult
                {
                    ReplyText = "Fiverr external memory storage is not ready yet.",
                    UsedFallback = true,
                    Language = language,
                    PlatformId = Platform.Id
                };
            }

            return _replyLearning.SuggestReply(Platform.Id, incomingText, language);
        }

        public void RememberPair(string incomingText, string replyText, string language)
        {
            if (!StorageReady)
            {
                return;
            }

            _replyLearning.RememberPair(Platform.Id, incomingText, replyText, language);
        }

        public ConversationSnapshot DraftReply(string replyText)
        {
            return _messagingAutomation.DraftReply(Platform, replyText);
        }

        public bool OpenInboxPage()
        {
            try
            {
                Process.Start(InboxUrl);
                return true;
            }
            catch
            {
                return false;
            }
        }
    }
}
