// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

using System;
using System.Linq;

namespace DeskCallAssistant
{
    public sealed class LanguageDetectionService
    {
        private static readonly string[] BanglishTokens =
        {
            "ami", "tumi", "apni", "valo", "bhalo", "kemon", "asen", "acho", "accho",
            "dhonnobad", "shukriya", "thik", "ki", "keno", "kisu", "ektu",
            "pore", "reply", "dibo", "dicchi", "korbo", "hobe", "lagbe",
            "message", "janai", "janabo", "ase", "nai", "na", "acha", "assalamu",
            "walaikum", "bhai", "apu"
        };

        public string DetectLanguage(string message, string fallbackLanguage)
        {
            if (string.IsNullOrWhiteSpace(message))
            {
                return NormalizeLanguage(fallbackLanguage, "English");
            }

            if (ContainsJapaneseScript(message))
            {
                return "Japanese";
            }

            if (ContainsBengaliScript(message))
            {
                return "Bengali";
            }

            var normalizedLatin = NormalizeLatin(message);
            if (LooksLikeBanglish(normalizedLatin))
            {
                return "Banglish";
            }

            if (LooksMostlyEnglish(normalizedLatin))
            {
                return "English";
            }

            return NormalizeLanguage(fallbackLanguage, "English");
        }

        private static bool ContainsJapaneseScript(string message)
        {
            return message.Any(ch =>
                (ch >= '\u3040' && ch <= '\u30ff') ||
                (ch >= '\u4e00' && ch <= '\u9faf'));
        }

        private static bool ContainsBengaliScript(string message)
        {
            return message.Any(ch => ch >= '\u0980' && ch <= '\u09ff');
        }

        private static bool LooksLikeBanglish(string normalizedLatin)
        {
            if (string.IsNullOrWhiteSpace(normalizedLatin))
            {
                return false;
            }

            var tokens = normalizedLatin
                .Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
            if (tokens.Length == 0)
            {
                return false;
            }

            var hits = tokens.Count(token => BanglishTokens.Contains(token));
            if (hits >= 2)
            {
                return true;
            }

            return hits >= 1 && ContainsAny(normalizedLatin, "kemon", "bhalo", "dhonnobad", "assalamu");
        }

        private static bool LooksMostlyEnglish(string normalizedLatin)
        {
            return normalizedLatin.Any(ch => ch >= 'a' && ch <= 'z');
        }

        private static string NormalizeLatin(string value)
        {
            return new string(value
                .ToLowerInvariant()
                .Select(ch => char.IsLetterOrDigit(ch) ? ch : ' ')
                .ToArray());
        }

        private static bool ContainsAny(string text, params string[] values)
        {
            foreach (var value in values)
            {
                if (text.IndexOf(value, StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    return true;
                }
            }

            return false;
        }

        private static string NormalizeLanguage(string language, string fallback)
        {
            if (string.IsNullOrWhiteSpace(language))
            {
                return fallback;
            }

            if (language.Equals("Bengali", StringComparison.OrdinalIgnoreCase) ||
                language.Equals("English", StringComparison.OrdinalIgnoreCase) ||
                language.Equals("Japanese", StringComparison.OrdinalIgnoreCase) ||
                language.Equals("Banglish", StringComparison.OrdinalIgnoreCase))
            {
                return language;
            }

            return fallback;
        }
    }
}
