// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace DeskCallAssistant
{
    public sealed class LocalLearningService
    {
        private sealed class LearningRecord
        {
            public string Phrase { get; set; }

            public int Count { get; set; }

            public long LastUsedUtcTicks { get; set; }

            public string Source { get; set; }
        }

        private readonly string _storagePath;

        public LocalLearningService()
        {
            var root = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                "DeskCallAssistant");
            Directory.CreateDirectory(root);
            _storagePath = Path.Combine(root, "LocalLearning.tsv");
        }

        public string StoragePath
        {
            get { return _storagePath; }
        }

        public void RememberPhrase(string phrase, string source)
        {
            AppPolicy.EnsureLocalOnlyLearning();

            var normalizedPhrase = NormalizePhrase(phrase);
            if (string.IsNullOrWhiteSpace(normalizedPhrase))
            {
                return;
            }

            var records = LoadRecords();
            var key = normalizedPhrase.ToLowerInvariant();
            LearningRecord existing;
            if (!records.TryGetValue(key, out existing))
            {
                existing = new LearningRecord
                {
                    Phrase = normalizedPhrase,
                    Count = 0,
                    Source = string.IsNullOrWhiteSpace(source) ? "local" : source.Trim()
                };
                records[key] = existing;
            }

            existing.Phrase = normalizedPhrase;
            existing.Count += 1;
            existing.LastUsedUtcTicks = DateTime.UtcNow.Ticks;
            existing.Source = string.IsNullOrWhiteSpace(source) ? existing.Source : source.Trim();

            SaveRecords(records.Values);
        }

        public string[] GetSuggestions(string currentText, int maxCount)
        {
            AppPolicy.EnsureLocalOnlyLearning();

            var records = LoadRecords().Values;
            if (maxCount <= 0)
            {
                return new string[0];
            }

            var normalizedInput = NormalizePhrase(currentText);
            if (string.IsNullOrWhiteSpace(normalizedInput))
            {
                return records
                    .OrderByDescending(item => item.Count)
                    .ThenByDescending(item => item.LastUsedUtcTicks)
                    .Select(item => item.Phrase)
                    .Take(maxCount)
                    .ToArray();
            }

            return records
                .Select(item => new
                {
                    Phrase = item.Phrase,
                    Score = Score(item, normalizedInput),
                    Count = item.Count,
                    LastUsedUtcTicks = item.LastUsedUtcTicks
                })
                .Where(item => item.Score > 0)
                .OrderByDescending(item => item.Score)
                .ThenByDescending(item => item.Count)
                .ThenByDescending(item => item.LastUsedUtcTicks)
                .Select(item => item.Phrase)
                .Take(maxCount)
                .ToArray();
        }

        private Dictionary<string, LearningRecord> LoadRecords()
        {
            var results = new Dictionary<string, LearningRecord>(StringComparer.OrdinalIgnoreCase);

            if (!File.Exists(_storagePath))
            {
                return results;
            }

            foreach (var line in File.ReadAllLines(_storagePath))
            {
                if (string.IsNullOrWhiteSpace(line))
                {
                    continue;
                }

                var parts = line.Split('\t');
                if (parts.Length < 4)
                {
                    continue;
                }

                var phrase = NormalizePhrase(parts[0]);
                if (string.IsNullOrWhiteSpace(phrase))
                {
                    continue;
                }

                int count;
                long lastUsedUtcTicks;
                if (!int.TryParse(parts[1], out count))
                {
                    count = 0;
                }

                if (!long.TryParse(parts[2], out lastUsedUtcTicks))
                {
                    lastUsedUtcTicks = 0;
                }

                results[phrase.ToLowerInvariant()] = new LearningRecord
                {
                    Phrase = phrase,
                    Count = count,
                    LastUsedUtcTicks = lastUsedUtcTicks,
                    Source = parts[3]
                };
            }

            return results;
        }

        private void SaveRecords(IEnumerable<LearningRecord> records)
        {
            var lines = records
                .OrderByDescending(item => item.Count)
                .ThenBy(item => item.Phrase)
                .Select(item => string.Format(
                    "{0}\t{1}\t{2}\t{3}",
                    NormalizePhrase(item.Phrase),
                    item.Count,
                    item.LastUsedUtcTicks,
                    NormalizeField(item.Source)))
                .ToArray();

            File.WriteAllLines(_storagePath, lines);
        }

        private static int Score(LearningRecord record, string normalizedInput)
        {
            var phrase = record.Phrase ?? string.Empty;
            if (phrase.Equals(normalizedInput, StringComparison.OrdinalIgnoreCase))
            {
                return 1000;
            }

            if (phrase.StartsWith(normalizedInput, StringComparison.OrdinalIgnoreCase))
            {
                return 800;
            }

            if (phrase.IndexOf(normalizedInput, StringComparison.OrdinalIgnoreCase) >= 0)
            {
                return 500;
            }

            var inputWords = normalizedInput.Split(' ');
            var score = 0;
            foreach (var inputWord in inputWords)
            {
                if (inputWord.Length < 3)
                {
                    continue;
                }

                if (phrase.IndexOf(inputWord, StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    score += 100;
                }
            }

            return score;
        }

        private static string NormalizePhrase(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return string.Empty;
            }

            return value
                .Replace('\r', ' ')
                .Replace('\n', ' ')
                .Replace('\t', ' ')
                .Trim();
        }

        private static string NormalizeField(string value)
        {
            return NormalizePhrase(value);
        }
    }
}
