// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;

namespace DeskCallAssistant
{
    public sealed class MainForm : Form
    {
        private readonly AppSettingsService _appSettingsService = new AppSettingsService();
        private readonly CallAutomationService _callAutomation = new CallAutomationService();
        private readonly ComputePolicyService _computePolicy = new ComputePolicyService();
        private readonly LocalLearningService _learning = new LocalLearningService();
        private readonly MessagingAutomationService _messagingAutomation = new MessagingAutomationService();
        private readonly MessagingReplyLearningService _replyLearning = new MessagingReplyLearningService();
        private readonly StorageLocationService _storageLocations = new StorageLocationService();
        private readonly StartupRegistrationService _startupRegistration = new StartupRegistrationService();
        private readonly SpeechService _speech = new SpeechService();
        private readonly Timer _scanTimer = new Timer();
        private readonly Timer _replyTimer = new Timer();
        private readonly Timer _settingsSaveTimer = new Timer();
        private readonly NotifyIcon _trayIcon = new NotifyIcon();
        private readonly ContextMenuStrip _trayMenu = new ContextMenuStrip();
        private readonly ToolStripMenuItem _trayShowMenuItem = new ToolStripMenuItem();
        private readonly ToolStripMenuItem _traySpeakStopMenuItem = new ToolStripMenuItem();
        private readonly ToolStripMenuItem _trayExitMenuItem = new ToolStripMenuItem();
        private readonly Panel _scrollHost = new Panel();
        private readonly TableLayoutPanel _rootLayout = new TableLayoutPanel();
        private readonly FiverrAssistantService _fiverrAssistant;
        private readonly Panel _callModeBar = new Panel();
        private readonly Panel _messageModeBar = new Panel();
        private readonly Panel _voiceModeBar = new Panel();
        private readonly Label _callModeStateLabel = new Label();
        private readonly Label _messageModeStateLabel = new Label();
        private readonly Label _voiceModeStateLabel = new Label();
        private readonly Button _callModeToggleButton = new Button();
        private readonly Button _messageModeToggleButton = new Button();
        private readonly Button _voiceModeToggleButton = new Button();

        private readonly CheckBox _autoAnswerCheckBox = new CheckBox();
        private readonly CheckBox _manualTalkCheckBox = new CheckBox();
        private readonly CheckBox _preferGpuCheckBox = new CheckBox();
        private readonly CheckBox _replyAssistantCheckBox = new CheckBox();
        private readonly CheckBox _autoSendReplyCheckBox = new CheckBox();
        private readonly CheckBox _openFiverrWhenReplyAssistantStartsCheckBox = new CheckBox();
        private readonly CheckBox _startWithWindowsCheckBox = new CheckBox();
        private readonly CheckBox _minimizeToTrayCheckBox = new CheckBox();
        private readonly NumericUpDown _scanIntervalSeconds = new NumericUpDown();
        private readonly NumericUpDown _replyIntervalSeconds = new NumericUpDown();
        private readonly TextBox _processNamesTextBox = new TextBox();
        private readonly TextBox _buttonLabelsTextBox = new TextBox();
        private readonly TextBox _computeStatusTextBox = new TextBox();
        private readonly TextBox _speechTextBox = new TextBox();
        private readonly TextBox _incomingMessageTextBox = new TextBox();
        private readonly TextBox _generatedReplyTextBox = new TextBox();
        private readonly TextBox _fiverrStatusTextBox = new TextBox();
        private readonly TextBox _fiverrIncomingMessageTextBox = new TextBox();
        private readonly TextBox _fiverrGeneratedReplyTextBox = new TextBox();
        private readonly TextBox _microphoneGuideTextBox = new TextBox();
        private readonly ComboBox _voicesComboBox = new ComboBox();
        private readonly ComboBox _replyPlatformComboBox = new ComboBox();
        private readonly ComboBox _replyLanguageComboBox = new ComboBox();
        private readonly ComboBox _fiverrLanguageComboBox = new ComboBox();
        private readonly TrackBar _rateTrackBar = new TrackBar();
        private readonly TrackBar _volumeTrackBar = new TrackBar();
        private readonly TextBox _logTextBox = new TextBox();
        private readonly Button _scanNowButton = new Button();
        private readonly Button _inspectButtonsButton = new Button();
        private readonly Button _rememberPhraseButton = new Button();
        private readonly Button _speakButton = new Button();
        private readonly Button _stopSpeechButton = new Button();
        private readonly Button _detectMessageButton = new Button();
        private readonly Button _detectFiverrMessageButton = new Button();
        private readonly Button _generateFiverrReplyButton = new Button();
        private readonly Button _learnFiverrPairButton = new Button();
        private readonly Button _draftFiverrReplyButton = new Button();
        private readonly Button _openFiverrInboxButton = new Button();
        private readonly Button _generateReplyButton = new Button();
        private readonly Button _learnReplyPatternButton = new Button();
        private readonly Button _draftReplyButton = new Button();
        private readonly Button _sendReplyButton = new Button();
        private readonly ListBox _suggestionsListBox = new ListBox();
        private readonly Label _statusLabel = new Label();

        private bool _forceExitFromTray;
        private bool _scanInProgress;
        private bool _settingsLoaded;
        private bool _trayBalloonShown;
        private string _lastProcessedReplyKey = string.Empty;

        public MainForm()
        {
            _fiverrAssistant = new FiverrAssistantService(_messagingAutomation, _storageLocations);

            Text = "Desk Call Assistant";
            StartPosition = FormStartPosition.CenterScreen;
            MinimumSize = new Size(900, 700);
            ClientSize = new Size(1180, 960);
            KeyPreview = true;

            InitializeLayout();
            InitializeTrayIcon();
            LoadVoices();
            LoadMessagingPlatforms();
            LoadReplyLanguages();
            LoadFiverrLanguages();
            LoadSettingsFromDisk();
            UpdateComputeStatus();
            UpdateLearningSuggestions();
            _fiverrStatusTextBox.Text = BuildFiverrStatus();
            UpdateActivityDashboard();

            _scanTimer.Tick += ScanTimerOnTick;
            _replyTimer.Tick += ReplyTimerOnTick;
            _settingsSaveTimer.Interval = 700;
            _settingsSaveTimer.Tick += SettingsSaveTimerOnTick;
            KeyDown += MainFormOnKeyDown;

            UpdateTimerState();
            UpdateReplyTimerState();
            Log("Ready. Configure call automation, speech, tray behavior, and message reply automation from the panels above.");
        }

        protected override void OnResize(EventArgs e)
        {
            base.OnResize(e);
            UpdateScrollableLayoutWidth();

            if (WindowState == FormWindowState.Minimized && _minimizeToTrayCheckBox.Checked)
            {
                HideToTray("Desk Call Assistant is still running in the system tray.");
            }
        }

        protected override void OnFormClosing(FormClosingEventArgs e)
        {
            if (!_forceExitFromTray &&
                _minimizeToTrayCheckBox.Checked &&
                e.CloseReason == CloseReason.UserClosing)
            {
                e.Cancel = true;
                HideToTray("Desk Call Assistant was minimized to the system tray.");
                ScheduleSettingsSave();
                return;
            }

            SaveSettingsToDisk();
            _scanTimer.Stop();
            _replyTimer.Stop();
            _settingsSaveTimer.Stop();
            _trayIcon.Visible = false;
            _trayIcon.Dispose();
            _trayMenu.Dispose();
            _speech.Dispose();

            base.OnFormClosing(e);
        }

        private void InitializeLayout()
        {
            _scrollHost.Dock = DockStyle.Fill;
            _scrollHost.AutoScroll = true;
            _scrollHost.Resize += (_, __) => UpdateScrollableLayoutWidth();
            Controls.Add(_scrollHost);

            _rootLayout.AutoSize = true;
            _rootLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            _rootLayout.GrowStyle = TableLayoutPanelGrowStyle.FixedSize;
            _rootLayout.Location = new Point(0, 0);
            _rootLayout.Padding = new Padding(12);
            _rootLayout.Margin = new Padding(0);
            _rootLayout.ColumnCount = 1;
            _rootLayout.RowCount = 8;
            _rootLayout.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            _rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
            _rootLayout.RowStyles.Clear();
            _rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 150f));
            _rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 180f));
            _rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 190f));
            _rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 430f));
            _rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 290f));
            _rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 290f));
            _rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 260f));
            _rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34f));
            _scrollHost.Controls.Add(_rootLayout);

            _rootLayout.Controls.Add(BuildLiveDashboard(), 0, 0);
            _rootLayout.Controls.Add(BuildAutomationPanel(), 0, 1);
            _rootLayout.Controls.Add(BuildComputePanel(), 0, 2);
            _rootLayout.Controls.Add(BuildSpeechPanel(), 0, 3);
            _rootLayout.Controls.Add(BuildReplyAssistantPanel(), 0, 4);
            _rootLayout.Controls.Add(BuildFiverrAssistantPanel(), 0, 5);
            _rootLayout.Controls.Add(BuildLogPanel(), 0, 6);
            _rootLayout.Controls.Add(BuildStatusPanel(), 0, 7);

            UpdateScrollableLayoutWidth();
        }

        private void UpdateScrollableLayoutWidth()
        {
            if (!_scrollHost.IsHandleCreated && _scrollHost.Width <= 0)
            {
                return;
            }

            var targetWidth = Math.Max(_scrollHost.ClientSize.Width - 1, MinimumSize.Width - 40);
            if (targetWidth > 0)
            {
                _rootLayout.Width = targetWidth;
            }
        }

        private Control BuildLiveDashboard()
        {
            var group = new GroupBox
            {
                Text = "Live controls",
                Dock = DockStyle.Fill
            };

            var layout = new TableLayoutPanel
            {
                Dock = DockStyle.Fill,
                Padding = new Padding(10),
                ColumnCount = 3,
                RowCount = 1
            };
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.34f));

            layout.Controls.Add(BuildModeCard(
                _callModeBar,
                "\uE717",
                "Calls",
                _callModeStateLabel,
                _callModeToggleButton,
                (_, __) => _autoAnswerCheckBox.Checked = !_autoAnswerCheckBox.Checked), 0, 0);

            layout.Controls.Add(BuildModeCard(
                _messageModeBar,
                "\uE8BD",
                "Messages",
                _messageModeStateLabel,
                _messageModeToggleButton,
                (_, __) => _replyAssistantCheckBox.Checked = !_replyAssistantCheckBox.Checked), 1, 0);

            layout.Controls.Add(BuildModeCard(
                _voiceModeBar,
                "\uE720",
                "Voice",
                _voiceModeStateLabel,
                _voiceModeToggleButton,
                (_, __) =>
                {
                    if (_manualTalkCheckBox.Checked)
                    {
                        _manualTalkCheckBox.Checked = false;
                    }
                    else
                    {
                        ToggleSpeechHotkey();
                    }
                }), 2, 0);

            group.Controls.Add(layout);
            return group;
        }

        private static Control BuildModeCard(
            Panel statusBar,
            string iconText,
            string title,
            Label stateLabel,
            Button actionButton,
            EventHandler action)
        {
            var card = new TableLayoutPanel
            {
                Dock = DockStyle.Fill,
                Margin = new Padding(8),
                BackColor = Color.White,
                ColumnCount = 1,
                RowCount = 4
            };
            card.RowStyles.Add(new RowStyle(SizeType.Absolute, 8f));
            card.RowStyles.Add(new RowStyle(SizeType.Absolute, 42f));
            card.RowStyles.Add(new RowStyle(SizeType.Percent, 100f));
            card.RowStyles.Add(new RowStyle(SizeType.Absolute, 38f));

            statusBar.Dock = DockStyle.Fill;
            statusBar.BackColor = Color.Silver;

            var iconLabel = new Label
            {
                Dock = DockStyle.Fill,
                Font = new Font("Segoe MDL2 Assets", 24f, FontStyle.Regular),
                Text = iconText,
                TextAlign = ContentAlignment.MiddleCenter
            };

            var textPanel = new TableLayoutPanel
            {
                Dock = DockStyle.Fill,
                ColumnCount = 1,
                RowCount = 2,
                Padding = new Padding(6, 0, 6, 0)
            };
            textPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 28f));
            textPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100f));
            textPanel.Controls.Add(new Label
            {
                Text = title,
                Dock = DockStyle.Fill,
                Font = new Font("Segoe UI", 11f, FontStyle.Bold),
                TextAlign = ContentAlignment.MiddleCenter
            }, 0, 0);

            stateLabel.Dock = DockStyle.Fill;
            stateLabel.Font = new Font("Segoe UI", 10f, FontStyle.Regular);
            stateLabel.TextAlign = ContentAlignment.TopCenter;
            textPanel.Controls.Add(stateLabel, 0, 1);

            actionButton.Dock = DockStyle.Fill;
            actionButton.FlatStyle = FlatStyle.Flat;
            actionButton.FlatAppearance.BorderSize = 0;
            actionButton.BackColor = Color.FromArgb(235, 238, 245);
            actionButton.Click += action;

            card.Controls.Add(statusBar, 0, 0);
            card.Controls.Add(iconLabel, 0, 1);
            card.Controls.Add(textPanel, 0, 2);
            card.Controls.Add(actionButton, 0, 3);
            return card;
        }

        private void InitializeTrayIcon()
        {
            _trayShowMenuItem.Click += (_, __) => RestoreFromTray();
            _traySpeakStopMenuItem.Click += (_, __) => ToggleSpeechHotkey();
            _trayExitMenuItem.Text = "Exit";
            _trayExitMenuItem.Click += (_, __) => ExitFromTray();
            _trayMenu.Opening += (_, __) =>
            {
                _trayShowMenuItem.Text = Visible ? "Bring to front" : "Show window";
                _traySpeakStopMenuItem.Text = _speech.IsSpeaking ? "Stop speech (F9)" : "Speak draft (F9)";
            };

            _trayMenu.Items.Add(_trayShowMenuItem);
            _trayMenu.Items.Add(_traySpeakStopMenuItem);
            _trayMenu.Items.Add(new ToolStripSeparator());
            _trayMenu.Items.Add(_trayExitMenuItem);

            _trayIcon.Text = "Desk Call Assistant";
            _trayIcon.Icon = SystemIcons.Application;
            _trayIcon.ContextMenuStrip = _trayMenu;
            _trayIcon.Visible = true;
            _trayIcon.DoubleClick += (_, __) => RestoreFromTray();
        }

        private Control BuildAutomationPanel()
        {
            var group = new GroupBox
            {
                Text = "Auto-answer setup",
                Dock = DockStyle.Fill
            };

            var layout = new TableLayoutPanel
            {
                Dock = DockStyle.Fill,
                Padding = new Padding(10),
                ColumnCount = 4,
                RowCount = 3
            };
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 180f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 180f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36f));
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 42f));

            _autoAnswerCheckBox.Text = "Enable auto-answer";
            _autoAnswerCheckBox.Dock = DockStyle.Fill;
            _autoAnswerCheckBox.CheckedChanged += (_, __) =>
            {
                UpdateTimerState();
                ScheduleSettingsSave();
            };

            _scanIntervalSeconds.Minimum = 1;
            _scanIntervalSeconds.Maximum = 30;
            _scanIntervalSeconds.Value = 2;
            _scanIntervalSeconds.Dock = DockStyle.Left;
            _scanIntervalSeconds.Width = 80;
            _scanIntervalSeconds.ValueChanged += (_, __) =>
            {
                UpdateTimerState();
                ScheduleSettingsSave();
            };

            var intervalPanel = new FlowLayoutPanel
            {
                Dock = DockStyle.Fill,
                FlowDirection = FlowDirection.LeftToRight,
                WrapContents = false
            };
            intervalPanel.Controls.Add(new Label
            {
                Text = "Scan every",
                AutoSize = true,
                TextAlign = ContentAlignment.MiddleLeft,
                Padding = new Padding(0, 7, 0, 0)
            });
            intervalPanel.Controls.Add(_scanIntervalSeconds);
            intervalPanel.Controls.Add(new Label
            {
                Text = "seconds",
                AutoSize = true,
                TextAlign = ContentAlignment.MiddleLeft,
                Padding = new Padding(0, 7, 0, 0)
            });

            _processNamesTextBox.Multiline = true;
            _processNamesTextBox.ScrollBars = ScrollBars.Vertical;
            _processNamesTextBox.Dock = DockStyle.Fill;
            _processNamesTextBox.Text = "chrome\r\nmsedge\r\nWhatsApp\r\nMessenger";
            _processNamesTextBox.TextChanged += (_, __) => ScheduleSettingsSave();

            _buttonLabelsTextBox.Multiline = true;
            _buttonLabelsTextBox.ScrollBars = ScrollBars.Vertical;
            _buttonLabelsTextBox.Dock = DockStyle.Fill;
            _buttonLabelsTextBox.Text = "Answer\r\nAccept\r\nPick up\r\nJoin";
            _buttonLabelsTextBox.TextChanged += (_, __) => ScheduleSettingsSave();

            _scanNowButton.Text = "Scan and answer now";
            _scanNowButton.AutoSize = true;
            _scanNowButton.Click += (_, __) => AttemptAnswer(true);

            _inspectButtonsButton.Text = "Inspect matching buttons";
            _inspectButtonsButton.AutoSize = true;
            _inspectButtonsButton.Click += (_, __) => InspectButtons();

            var actionsPanel = new FlowLayoutPanel
            {
                Dock = DockStyle.Fill,
                FlowDirection = FlowDirection.LeftToRight
            };
            actionsPanel.Controls.Add(_scanNowButton);
            actionsPanel.Controls.Add(_inspectButtonsButton);

            layout.Controls.Add(_autoAnswerCheckBox, 0, 0);
            layout.SetColumnSpan(_autoAnswerCheckBox, 2);
            layout.Controls.Add(intervalPanel, 2, 0);
            layout.SetColumnSpan(intervalPanel, 2);

            layout.Controls.Add(new Label
            {
                Text = "Target process names\r\n(one per line)",
                AutoSize = true,
                Dock = DockStyle.Fill
            }, 0, 1);
            layout.Controls.Add(_processNamesTextBox, 1, 1);
            layout.Controls.Add(new Label
            {
                Text = "Answer button labels\r\n(one per line)",
                AutoSize = true,
                Dock = DockStyle.Fill
            }, 2, 1);
            layout.Controls.Add(_buttonLabelsTextBox, 3, 1);
            layout.Controls.Add(actionsPanel, 0, 2);
            layout.SetColumnSpan(actionsPanel, 4);

            group.Controls.Add(layout);
            return group;
        }

        private Control BuildComputePanel()
        {
            var group = new GroupBox
            {
                Text = "Compute, startup, and privacy policy",
                Dock = DockStyle.Fill
            };

            var layout = new TableLayoutPanel
            {
                Dock = DockStyle.Fill,
                Padding = new Padding(10),
                ColumnCount = 1,
                RowCount = 2
            };
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 54f));
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100f));

            _preferGpuCheckBox.Text = "Prefer GPU for local bot workloads";
            _preferGpuCheckBox.AutoSize = true;
            _preferGpuCheckBox.CheckedChanged += (_, __) =>
            {
                UpdateComputeStatus();
                ScheduleSettingsSave();
                Log(_preferGpuCheckBox.Checked
                    ? "GPU preference enabled for local bot workloads."
                    : "GPU preference disabled for local bot workloads.");
            };

            _startWithWindowsCheckBox.Text = "Start with Windows";
            _startWithWindowsCheckBox.AutoSize = true;
            _startWithWindowsCheckBox.CheckedChanged += (_, __) =>
            {
                ApplyStartupRegistrationFromUi();
                ScheduleSettingsSave();
            };

            _minimizeToTrayCheckBox.Text = "Minimize to system tray";
            _minimizeToTrayCheckBox.AutoSize = true;
            _minimizeToTrayCheckBox.CheckedChanged += (_, __) => ScheduleSettingsSave();

            var optionsPanel = new FlowLayoutPanel
            {
                Dock = DockStyle.Fill,
                FlowDirection = FlowDirection.LeftToRight
            };
            optionsPanel.Controls.Add(_preferGpuCheckBox);
            optionsPanel.Controls.Add(_startWithWindowsCheckBox);
            optionsPanel.Controls.Add(_minimizeToTrayCheckBox);

            _computeStatusTextBox.Multiline = true;
            _computeStatusTextBox.ReadOnly = true;
            _computeStatusTextBox.ScrollBars = ScrollBars.Vertical;
            _computeStatusTextBox.Dock = DockStyle.Fill;
            _computeStatusTextBox.BackColor = Color.White;

            layout.Controls.Add(optionsPanel, 0, 0);
            layout.Controls.Add(_computeStatusTextBox, 0, 1);
            group.Controls.Add(layout);
            return group;
        }

        private Control BuildSpeechPanel()
        {
            var group = new GroupBox
            {
                Text = "Typed speech, hotkeys, and microphone routing",
                Dock = DockStyle.Fill
            };

            var layout = new TableLayoutPanel
            {
                Dock = DockStyle.Fill,
                Padding = new Padding(10),
                ColumnCount = 4,
                RowCount = 7
            };
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 120f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 120f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 120f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 90f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 110f));
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 44f));

            _manualTalkCheckBox.Text = "Manual talk takeover (F8)";
            _manualTalkCheckBox.AutoSize = true;
            _manualTalkCheckBox.CheckedChanged += (_, __) =>
            {
                ApplyManualTalkMode();
                ScheduleSettingsSave();
            };

            _voicesComboBox.Dock = DockStyle.Fill;
            _voicesComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            _voicesComboBox.SelectedIndexChanged += (_, __) => ScheduleSettingsSave();

            _rateTrackBar.Dock = DockStyle.Fill;
            _rateTrackBar.Minimum = -5;
            _rateTrackBar.Maximum = 5;
            _rateTrackBar.TickFrequency = 1;
            _rateTrackBar.ValueChanged += (_, __) => ScheduleSettingsSave();

            _volumeTrackBar.Dock = DockStyle.Fill;
            _volumeTrackBar.Minimum = 0;
            _volumeTrackBar.Maximum = 100;
            _volumeTrackBar.TickFrequency = 10;
            _volumeTrackBar.Value = 100;
            _volumeTrackBar.ValueChanged += (_, __) => ScheduleSettingsSave();

            _speechTextBox.Multiline = true;
            _speechTextBox.ScrollBars = ScrollBars.Vertical;
            _speechTextBox.Dock = DockStyle.Fill;
            _speechTextBox.Text = "Hello, please give me a moment.";
            _speechTextBox.TextChanged += (_, __) =>
            {
                UpdateLearningSuggestions();
                ScheduleSettingsSave();
            };

            _microphoneGuideTextBox.Multiline = true;
            _microphoneGuideTextBox.ReadOnly = true;
            _microphoneGuideTextBox.ScrollBars = ScrollBars.Vertical;
            _microphoneGuideTextBox.Dock = DockStyle.Fill;
            _microphoneGuideTextBox.BackColor = Color.White;
            _microphoneGuideTextBox.Text = BuildMicrophoneRoutingGuidance();

            _rememberPhraseButton.Text = "Remember";
            _rememberPhraseButton.Dock = DockStyle.Fill;
            _rememberPhraseButton.Click += (_, __) => RememberCurrentPhrase("manual-save");

            _speakButton.Text = "Speak";
            _speakButton.Dock = DockStyle.Fill;
            _speakButton.Click += (_, __) => SpeakCurrentText();

            _stopSpeechButton.Text = "Stop";
            _stopSpeechButton.Dock = DockStyle.Fill;
            _stopSpeechButton.Click += (_, __) =>
            {
                _speech.Stop();
                Log("Speech stopped.");
                SetStatus("Speech stopped.");
            };

            _suggestionsListBox.Dock = DockStyle.Fill;
            _suggestionsListBox.DoubleClick += (_, __) =>
            {
                if (_suggestionsListBox.SelectedItem == null)
                {
                    return;
                }

                _speechTextBox.Text = _suggestionsListBox.SelectedItem.ToString();
                _speechTextBox.SelectionStart = _speechTextBox.TextLength;
            };

            layout.Controls.Add(_manualTalkCheckBox, 0, 0);
            layout.SetColumnSpan(_manualTalkCheckBox, 2);
            layout.Controls.Add(new Label
            {
                Text = "Speech hotkey: F9 to speak or stop the current draft.",
                AutoSize = true,
                Dock = DockStyle.Fill
            }, 2, 0);
            layout.SetColumnSpan(layout.GetControlFromPosition(2, 0), 2);

            layout.Controls.Add(new Label { Text = "Voice", AutoSize = true, TextAlign = ContentAlignment.MiddleLeft }, 0, 1);
            layout.Controls.Add(_voicesComboBox, 1, 1);
            layout.Controls.Add(new Label { Text = "Rate", AutoSize = true, TextAlign = ContentAlignment.MiddleLeft }, 2, 1);
            layout.Controls.Add(_rateTrackBar, 3, 1);

            layout.Controls.Add(new Label { Text = "Volume", AutoSize = true, TextAlign = ContentAlignment.MiddleLeft }, 0, 2);
            layout.Controls.Add(_volumeTrackBar, 1, 2);
            layout.Controls.Add(new Label
            {
                Text = "Tip: keep Manual talk takeover off when you want the bot to speak.",
                AutoSize = true,
                Dock = DockStyle.Fill
            }, 2, 2);
            layout.SetColumnSpan(layout.GetControlFromPosition(2, 2), 2);

            layout.Controls.Add(new Label { Text = "Type what should be spoken", AutoSize = true, Dock = DockStyle.Fill }, 0, 3);
            layout.Controls.Add(_speechTextBox, 1, 3);
            layout.SetColumnSpan(_speechTextBox, 3);

            layout.Controls.Add(new Label { Text = "Microphone routing guide", AutoSize = true, Dock = DockStyle.Fill }, 0, 4);
            layout.Controls.Add(_microphoneGuideTextBox, 1, 4);
            layout.SetColumnSpan(_microphoneGuideTextBox, 3);

            layout.Controls.Add(new Label { Text = "Local suggestions", AutoSize = true, Dock = DockStyle.Fill }, 0, 5);
            layout.Controls.Add(_suggestionsListBox, 1, 5);
            layout.SetColumnSpan(_suggestionsListBox, 3);

            var actionPanel = new TableLayoutPanel
            {
                Dock = DockStyle.Fill,
                ColumnCount = 3,
                RowCount = 1
            };
            actionPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33f));
            actionPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33f));
            actionPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.34f));
            actionPanel.Controls.Add(_rememberPhraseButton, 0, 0);
            actionPanel.Controls.Add(_speakButton, 1, 0);
            actionPanel.Controls.Add(_stopSpeechButton, 2, 0);
            layout.Controls.Add(actionPanel, 1, 6);
            layout.SetColumnSpan(actionPanel, 3);

            group.Controls.Add(layout);
            return group;
        }

        private Control BuildReplyAssistantPanel()
        {
            var group = new GroupBox
            {
                Text = "Message reply assistant",
                Dock = DockStyle.Fill
            };

            var layout = new TableLayoutPanel
            {
                Dock = DockStyle.Fill,
                Padding = new Padding(10),
                ColumnCount = 4,
                RowCount = 6
            };
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 70f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 70f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 42f));
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100f));

            _replyAssistantCheckBox.Text = "Watch chats and prepare replies";
            _replyAssistantCheckBox.AutoSize = true;
            _replyAssistantCheckBox.CheckedChanged += (_, __) =>
            {
                UpdateReplyTimerState();
                ScheduleSettingsSave();
            };

            _replyIntervalSeconds.Minimum = 2;
            _replyIntervalSeconds.Maximum = 60;
            _replyIntervalSeconds.Value = 5;
            _replyIntervalSeconds.Width = 70;
            _replyIntervalSeconds.ValueChanged += (_, __) =>
            {
                UpdateReplyTimerState();
                ScheduleSettingsSave();
            };

            _autoSendReplyCheckBox.Text = "Auto-send reply";
            _autoSendReplyCheckBox.AutoSize = true;
            _autoSendReplyCheckBox.CheckedChanged += (_, __) => ScheduleSettingsSave();

            _openFiverrWhenReplyAssistantStartsCheckBox.Text = "Open Fiverr inbox when assistant starts";
            _openFiverrWhenReplyAssistantStartsCheckBox.AutoSize = true;
            _openFiverrWhenReplyAssistantStartsCheckBox.CheckedChanged += (_, __) => ScheduleSettingsSave();

            var topPanel = new FlowLayoutPanel
            {
                Dock = DockStyle.Fill,
                FlowDirection = FlowDirection.LeftToRight,
                WrapContents = false
            };
            topPanel.Controls.Add(_replyAssistantCheckBox);
            topPanel.Controls.Add(new Label
            {
                Text = "Check every",
                AutoSize = true,
                Padding = new Padding(10, 7, 0, 0)
            });
            topPanel.Controls.Add(_replyIntervalSeconds);
            topPanel.Controls.Add(new Label
            {
                Text = "seconds",
                AutoSize = true,
                Padding = new Padding(0, 7, 10, 0)
            });
            topPanel.Controls.Add(_autoSendReplyCheckBox);
            topPanel.Controls.Add(_openFiverrWhenReplyAssistantStartsCheckBox);

            _replyPlatformComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            _replyPlatformComboBox.Dock = DockStyle.Fill;
            _replyPlatformComboBox.SelectedIndexChanged += (_, __) => ScheduleSettingsSave();

            _replyLanguageComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            _replyLanguageComboBox.Dock = DockStyle.Fill;
            _replyLanguageComboBox.SelectedIndexChanged += (_, __) => ScheduleSettingsSave();

            _incomingMessageTextBox.Multiline = true;
            _incomingMessageTextBox.ScrollBars = ScrollBars.Vertical;
            _incomingMessageTextBox.Dock = DockStyle.Fill;
            _incomingMessageTextBox.TextChanged += (_, __) => ScheduleSettingsSave();

            _generatedReplyTextBox.Multiline = true;
            _generatedReplyTextBox.ScrollBars = ScrollBars.Vertical;
            _generatedReplyTextBox.Dock = DockStyle.Fill;
            _generatedReplyTextBox.TextChanged += (_, __) => ScheduleSettingsSave();

            _detectMessageButton.Text = "Detect";
            _detectMessageButton.AutoSize = true;
            _detectMessageButton.Click += (_, __) => DetectCurrentMessage(true);

            _generateReplyButton.Text = "Generate";
            _generateReplyButton.AutoSize = true;
            _generateReplyButton.Click += (_, __) => GenerateReplyFromCurrentInput(true);

            _learnReplyPatternButton.Text = "Learn pair";
            _learnReplyPatternButton.AutoSize = true;
            _learnReplyPatternButton.Click += (_, __) => RememberCurrentReplyPair();

            _draftReplyButton.Text = "Draft reply";
            _draftReplyButton.AutoSize = true;
            _draftReplyButton.Click += (_, __) => DraftCurrentReply();

            _sendReplyButton.Text = "Send reply";
            _sendReplyButton.AutoSize = true;
            _sendReplyButton.Click += (_, __) => SendCurrentReply();

            layout.Controls.Add(topPanel, 0, 0);
            layout.SetColumnSpan(topPanel, 4);

            layout.Controls.Add(new Label { Text = "Platform", AutoSize = true, Dock = DockStyle.Fill }, 0, 1);
            layout.Controls.Add(_replyPlatformComboBox, 1, 1);
            layout.Controls.Add(new Label { Text = "Reply language", AutoSize = true, Dock = DockStyle.Fill }, 2, 1);
            layout.Controls.Add(_replyLanguageComboBox, 3, 1);

            layout.Controls.Add(new Label { Text = "Latest incoming message", AutoSize = true, Dock = DockStyle.Fill }, 0, 2);
            layout.Controls.Add(_incomingMessageTextBox, 1, 2);
            layout.SetColumnSpan(_incomingMessageTextBox, 3);

            layout.Controls.Add(new Label { Text = "Generated reply", AutoSize = true, Dock = DockStyle.Fill }, 0, 3);
            layout.Controls.Add(_generatedReplyTextBox, 1, 3);
            layout.SetColumnSpan(_generatedReplyTextBox, 3);

            var buttonPanel = new FlowLayoutPanel
            {
                Dock = DockStyle.Fill,
                FlowDirection = FlowDirection.LeftToRight
            };
            buttonPanel.Controls.Add(_detectMessageButton);
            buttonPanel.Controls.Add(_generateReplyButton);
            buttonPanel.Controls.Add(_learnReplyPatternButton);
            buttonPanel.Controls.Add(_draftReplyButton);
            buttonPanel.Controls.Add(_sendReplyButton);
            layout.Controls.Add(buttonPanel, 0, 4);
            layout.SetColumnSpan(buttonPanel, 4);

            layout.Controls.Add(new Label
            {
                Text = "Messenger web: official desktop web is messenger.com. Facebook also has messaging inside facebook.com.",
                AutoSize = true,
                Dock = DockStyle.Fill
            }, 0, 5);
            layout.SetColumnSpan(layout.GetControlFromPosition(0, 5), 4);

            group.Controls.Add(layout);
            return group;
        }

        private Control BuildFiverrAssistantPanel()
        {
            var group = new GroupBox
            {
                Text = "Fiverr helper",
                Dock = DockStyle.Fill
            };

            var layout = new TableLayoutPanel
            {
                Dock = DockStyle.Fill,
                Padding = new Padding(10),
                ColumnCount = 4,
                RowCount = 5
            };
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 60f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 70f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 70f));
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100f));

            _fiverrStatusTextBox.Multiline = true;
            _fiverrStatusTextBox.ReadOnly = true;
            _fiverrStatusTextBox.ScrollBars = ScrollBars.Vertical;
            _fiverrStatusTextBox.Dock = DockStyle.Fill;
            _fiverrStatusTextBox.BackColor = Color.White;
            _fiverrStatusTextBox.Text = BuildFiverrStatus();

            _fiverrIncomingMessageTextBox.Multiline = true;
            _fiverrIncomingMessageTextBox.ScrollBars = ScrollBars.Vertical;
            _fiverrIncomingMessageTextBox.Dock = DockStyle.Fill;
            _fiverrIncomingMessageTextBox.TextChanged += (_, __) => ScheduleSettingsSave();

            _fiverrGeneratedReplyTextBox.Multiline = true;
            _fiverrGeneratedReplyTextBox.ScrollBars = ScrollBars.Vertical;
            _fiverrGeneratedReplyTextBox.Dock = DockStyle.Fill;
            _fiverrGeneratedReplyTextBox.TextChanged += (_, __) => ScheduleSettingsSave();

            _fiverrLanguageComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            _fiverrLanguageComboBox.Dock = DockStyle.Fill;
            _fiverrLanguageComboBox.SelectedIndexChanged += (_, __) => ScheduleSettingsSave();

            _openFiverrInboxButton.Text = "Open inbox";
            _openFiverrInboxButton.AutoSize = true;
            _openFiverrInboxButton.Click += (_, __) => OpenFiverrInbox();

            _detectFiverrMessageButton.Text = "Read open inbox";
            _detectFiverrMessageButton.AutoSize = true;
            _detectFiverrMessageButton.Click += (_, __) => DetectFiverrMessage();

            _generateFiverrReplyButton.Text = "Generate draft";
            _generateFiverrReplyButton.AutoSize = true;
            _generateFiverrReplyButton.Click += (_, __) => GenerateFiverrReply();

            _learnFiverrPairButton.Text = "Learn pair";
            _learnFiverrPairButton.AutoSize = true;
            _learnFiverrPairButton.Click += (_, __) => LearnFiverrPair();

            _draftFiverrReplyButton.Text = "Draft to inbox";
            _draftFiverrReplyButton.AutoSize = true;
            _draftFiverrReplyButton.Click += (_, __) => DraftFiverrReply();

            var header = new Label
            {
                Text = "This helper does not randomize refreshes, evade platform detection, send replies automatically, or store credentials. Open the official inbox page and use this panel to read and draft.",
                AutoSize = true,
                Dock = DockStyle.Fill
            };

            layout.Controls.Add(header, 0, 0);
            layout.SetColumnSpan(header, 4);
            layout.Controls.Add(new Label { Text = "Storage and safety", AutoSize = true, Dock = DockStyle.Fill }, 0, 1);
            layout.Controls.Add(_fiverrStatusTextBox, 1, 1);
            layout.SetColumnSpan(_fiverrStatusTextBox, 3);
            layout.Controls.Add(new Label { Text = "Language", AutoSize = true, Dock = DockStyle.Fill }, 0, 2);
            layout.Controls.Add(_fiverrLanguageComboBox, 1, 2);
            layout.Controls.Add(new Label { Text = "Latest Fiverr message", AutoSize = true, Dock = DockStyle.Fill }, 2, 2);
            layout.Controls.Add(_fiverrIncomingMessageTextBox, 3, 2);
            layout.Controls.Add(new Label { Text = "Draft reply", AutoSize = true, Dock = DockStyle.Fill }, 0, 3);
            layout.Controls.Add(_fiverrGeneratedReplyTextBox, 1, 3);
            layout.SetColumnSpan(_fiverrGeneratedReplyTextBox, 3);

            var buttonPanel = new FlowLayoutPanel
            {
                Dock = DockStyle.Fill,
                FlowDirection = FlowDirection.LeftToRight
            };
            buttonPanel.Controls.Add(_openFiverrInboxButton);
            buttonPanel.Controls.Add(_detectFiverrMessageButton);
            buttonPanel.Controls.Add(_generateFiverrReplyButton);
            buttonPanel.Controls.Add(_learnFiverrPairButton);
            buttonPanel.Controls.Add(_draftFiverrReplyButton);
            layout.Controls.Add(buttonPanel, 0, 4);
            layout.SetColumnSpan(buttonPanel, 4);

            group.Controls.Add(layout);
            return group;
        }

        private Control BuildLogPanel()
        {
            var group = new GroupBox
            {
                Text = "Activity log",
                Dock = DockStyle.Fill
            };

            _logTextBox.Multiline = true;
            _logTextBox.ReadOnly = true;
            _logTextBox.ScrollBars = ScrollBars.Vertical;
            _logTextBox.Dock = DockStyle.Fill;
            _logTextBox.BackColor = Color.White;

            group.Controls.Add(_logTextBox);
            return group;
        }

        private Control BuildStatusPanel()
        {
            _statusLabel.Dock = DockStyle.Fill;
            _statusLabel.TextAlign = ContentAlignment.MiddleLeft;
            return _statusLabel;
        }

        private void LoadVoices()
        {
            var voices = _speech.GetInstalledVoices();
            foreach (var voice in voices)
            {
                _voicesComboBox.Items.Add(voice);
            }

            if (_voicesComboBox.Items.Count > 0)
            {
                _voicesComboBox.SelectedIndex = 0;
            }
        }

        private void LoadMessagingPlatforms()
        {
            foreach (var platform in _messagingAutomation.GetSupportedPlatforms())
            {
                _replyPlatformComboBox.Items.Add(platform);
            }

            if (_replyPlatformComboBox.Items.Count > 0)
            {
                _replyPlatformComboBox.SelectedIndex = 0;
            }
        }

        private void LoadReplyLanguages()
        {
            _replyLanguageComboBox.Items.Add("Bengali");
            _replyLanguageComboBox.Items.Add("English");
            _replyLanguageComboBox.Items.Add("Japanese");
            _replyLanguageComboBox.Items.Add("Banglish");
            _replyLanguageComboBox.SelectedIndex = 0;
        }

        private void LoadFiverrLanguages()
        {
            _fiverrLanguageComboBox.Items.Add("Bengali");
            _fiverrLanguageComboBox.Items.Add("English");
            _fiverrLanguageComboBox.Items.Add("Japanese");
            _fiverrLanguageComboBox.Items.Add("Banglish");
            _fiverrLanguageComboBox.SelectedIndex = 0;
        }

        private void LoadSettingsFromDisk()
        {
            var settings = _appSettingsService.Load();
            _settingsLoaded = false;

            _autoAnswerCheckBox.Checked = settings.AutoAnswerEnabled;
            _scanIntervalSeconds.Value = NormalizeDecimal(settings.ScanIntervalSeconds, _scanIntervalSeconds.Minimum, _scanIntervalSeconds.Maximum, 2);
            _processNamesTextBox.Text = string.IsNullOrWhiteSpace(settings.ProcessNamesText) ? _processNamesTextBox.Text : settings.ProcessNamesText;
            _buttonLabelsTextBox.Text = string.IsNullOrWhiteSpace(settings.ButtonLabelsText) ? _buttonLabelsTextBox.Text : settings.ButtonLabelsText;
            _preferGpuCheckBox.Checked = settings.PreferGpu;
            _startWithWindowsCheckBox.Checked = settings.StartWithWindows || _startupRegistration.IsEnabled();
            _minimizeToTrayCheckBox.Checked = settings.MinimizeToTray;
            _manualTalkCheckBox.Checked = settings.ManualTalkEnabled;

            if (!string.IsNullOrWhiteSpace(settings.VoiceName))
            {
                SelectComboItemByText(_voicesComboBox, settings.VoiceName);
            }

            _rateTrackBar.Value = NormalizeInt(settings.VoiceRate, _rateTrackBar.Minimum, _rateTrackBar.Maximum, 0);
            _volumeTrackBar.Value = NormalizeInt(settings.VoiceVolume, _volumeTrackBar.Minimum, _volumeTrackBar.Maximum, 100);
            _speechTextBox.Text = string.IsNullOrWhiteSpace(settings.SpeechText) ? _speechTextBox.Text : settings.SpeechText;

            _replyAssistantCheckBox.Checked = settings.ReplyAssistantEnabled;
            _autoSendReplyCheckBox.Checked = settings.AutoSendReplyEnabled;
            _openFiverrWhenReplyAssistantStartsCheckBox.Checked = settings.OpenFiverrOnAssistantStarts;
            _replyIntervalSeconds.Value = NormalizeDecimal(settings.ReplyIntervalSeconds, _replyIntervalSeconds.Minimum, _replyIntervalSeconds.Maximum, 5);
            SelectPlatformById(settings.ReplyPlatformId);
            SelectComboItemByText(_replyLanguageComboBox, settings.ReplyLanguage);
            _incomingMessageTextBox.Text = settings.IncomingMessageText ?? string.Empty;
            _generatedReplyTextBox.Text = settings.GeneratedReplyText ?? string.Empty;
            SelectComboItemByText(_fiverrLanguageComboBox, settings.FiverrLanguage);
            _fiverrIncomingMessageTextBox.Text = settings.FiverrIncomingMessageText ?? string.Empty;
            _fiverrGeneratedReplyTextBox.Text = settings.FiverrGeneratedReplyText ?? string.Empty;

            if (settings.WindowWidth > MinimumSize.Width)
            {
                Width = settings.WindowWidth;
            }

            if (settings.WindowHeight > MinimumSize.Height)
            {
                Height = settings.WindowHeight;
            }

            _settingsLoaded = true;
            ApplyStartupRegistrationFromUi();
            ApplyManualTalkMode();
        }

        private void SaveSettingsToDisk()
        {
            if (!_settingsLoaded)
            {
                return;
            }

            _appSettingsService.Save(BuildCurrentSettings());
        }

        private AppSettings BuildCurrentSettings()
        {
            var bounds = WindowState == FormWindowState.Normal ? Bounds : RestoreBounds;

            return new AppSettings
            {
                AutoAnswerEnabled = _autoAnswerCheckBox.Checked,
                ScanIntervalSeconds = _scanIntervalSeconds.Value,
                ProcessNamesText = _processNamesTextBox.Text,
                ButtonLabelsText = _buttonLabelsTextBox.Text,
                PreferGpu = _preferGpuCheckBox.Checked,
                StartWithWindows = _startWithWindowsCheckBox.Checked,
                MinimizeToTray = _minimizeToTrayCheckBox.Checked,
                ManualTalkEnabled = _manualTalkCheckBox.Checked,
                VoiceName = _voicesComboBox.SelectedItem as string,
                VoiceRate = _rateTrackBar.Value,
                VoiceVolume = _volumeTrackBar.Value,
                SpeechText = _speechTextBox.Text,
                ReplyAssistantEnabled = _replyAssistantCheckBox.Checked,
                AutoSendReplyEnabled = _autoSendReplyCheckBox.Checked,
                OpenFiverrOnAssistantStarts = _openFiverrWhenReplyAssistantStartsCheckBox.Checked,
                ReplyIntervalSeconds = _replyIntervalSeconds.Value,
                ReplyPlatformId = GetSelectedPlatformId(),
                ReplyLanguage = _replyLanguageComboBox.SelectedItem as string,
                IncomingMessageText = _incomingMessageTextBox.Text,
                GeneratedReplyText = _generatedReplyTextBox.Text,
                FiverrLanguage = _fiverrLanguageComboBox.SelectedItem as string,
                FiverrIncomingMessageText = _fiverrIncomingMessageTextBox.Text,
                FiverrGeneratedReplyText = _fiverrGeneratedReplyTextBox.Text,
                WindowWidth = bounds.Width,
                WindowHeight = bounds.Height
            };
        }

        private void SettingsSaveTimerOnTick(object sender, EventArgs e)
        {
            _settingsSaveTimer.Stop();
            SaveSettingsToDisk();
        }

        private void ScheduleSettingsSave()
        {
            if (!_settingsLoaded)
            {
                return;
            }

            _settingsSaveTimer.Stop();
            _settingsSaveTimer.Start();
        }

        private void ApplyStartupRegistrationFromUi()
        {
            try
            {
                _startupRegistration.SetEnabled(_startWithWindowsCheckBox.Checked, Application.ExecutablePath);
                UpdateComputeStatus();
            }
            catch (Exception ex)
            {
                Log("Startup registration error: " + ex.Message);
            }
        }

        private void UpdateComputeStatus()
        {
            var status = _computePolicy.GetStatus(_preferGpuCheckBox.Checked);
            _computeStatusTextBox.Text = string.Format(
                "{0}{1}{1}{2}{1}- Phrase memory path: {3}{1}- Reply pattern path: {4}{1}- Settings path: {5}{1}- Start with Windows: {6}{1}- Tray behavior: {7}",
                status.Summary,
                Environment.NewLine,
                AppPolicy.BuildPrivacySummary(_learning.StoragePath),
                _learning.StoragePath,
                _replyLearning.StoragePath,
                _appSettingsService.SettingsPath,
                _startWithWindowsCheckBox.Checked ? "enabled" : "disabled",
                _minimizeToTrayCheckBox.Checked ? "minimize to tray is enabled" : "window closes normally");

            _fiverrStatusTextBox.Text = BuildFiverrStatus();
        }

        private void UpdateActivityDashboard()
        {
            UpdateModeCard(
                _callModeBar,
                _callModeStateLabel,
                _callModeToggleButton,
                _autoAnswerCheckBox.Checked,
                _autoAnswerCheckBox.Checked ? "Watching" : "Idle",
                _autoAnswerCheckBox.Checked ? "Stop" : "Start",
                Color.FromArgb(43, 138, 62));

            UpdateModeCard(
                _messageModeBar,
                _messageModeStateLabel,
                _messageModeToggleButton,
                _replyAssistantCheckBox.Checked,
                _replyAssistantCheckBox.Checked ? "Checking chats" : "Idle",
                _replyAssistantCheckBox.Checked ? "Stop" : "Start",
                Color.FromArgb(30, 102, 245));

            var voiceActive = _speech.IsSpeaking && !_manualTalkCheckBox.Checked;
            var voiceStatus = _manualTalkCheckBox.Checked
                ? "Manual mic"
                : (voiceActive ? "Speaking" : "Ready");
            var voiceAction = _manualTalkCheckBox.Checked
                ? "Use bot"
                : (voiceActive ? "Stop" : "Speak");
            var voiceColor = _manualTalkCheckBox.Checked
                ? Color.FromArgb(230, 119, 0)
                : Color.FromArgb(112, 72, 232);

            UpdateModeCard(
                _voiceModeBar,
                _voiceModeStateLabel,
                _voiceModeToggleButton,
                true,
                voiceStatus,
                voiceAction,
                voiceColor);
        }

        private static void UpdateModeCard(
            Panel statusBar,
            Label stateLabel,
            Button actionButton,
            bool active,
            string stateText,
            string actionText,
            Color activeColor)
        {
            statusBar.BackColor = active ? activeColor : Color.Silver;
            stateLabel.Text = stateText;
            actionButton.Text = actionText;
            actionButton.BackColor = active
                ? Color.FromArgb(
                    System.Math.Min(activeColor.R + 170, 255),
                    System.Math.Min(activeColor.G + 170, 255),
                    System.Math.Min(activeColor.B + 170, 255))
                : Color.FromArgb(235, 238, 245);
        }

        private string BuildFiverrStatus()
        {
            return string.Format(
                "{0}{1}Official inbox URL: {2}{1}Credentials are not written into source code or helper storage.{1}CSS injection into Fiverr pages is intentionally not used.",
                _fiverrAssistant.StorageStatus,
                Environment.NewLine,
                _fiverrAssistant.InboxUrlValue);
        }

        private string BuildMicrophoneRoutingGuidance()
        {
            return string.Join(Environment.NewLine, new[]
            {
                "1. Install a virtual audio cable such as VB-CABLE or a mixer such as VoiceMeeter.",
                "2. Set the app's spoken output to your normal speaker path, then mirror that output into the virtual microphone path.",
                "3. In Messenger, WhatsApp, Telegram, or your browser call settings, choose the virtual cable as the microphone input.",
                "4. Use F9 to speak or stop the current draft quickly while watching the call.",
                "5. Use F8 for Manual talk takeover whenever you want to use your real microphone instead of the bot voice."
            });
        }

        private void UpdateTimerState()
        {
            _scanTimer.Stop();

            if (_autoAnswerCheckBox.Checked)
            {
                _scanTimer.Interval = (int)_scanIntervalSeconds.Value * 1000;
                _scanTimer.Start();
                SetStatus("Auto-answer is watching for incoming call buttons.");
            }
            else
            {
                SetStatus("Auto-answer is paused.");
            }

            UpdateActivityDashboard();
        }

        private void UpdateReplyTimerState()
        {
            _replyTimer.Stop();

            if (_replyAssistantCheckBox.Checked)
            {
                _replyTimer.Interval = (int)_replyIntervalSeconds.Value * 1000;
                _replyTimer.Start();
                Log("Reply assistant is watching supported chat windows.");

                if (_openFiverrWhenReplyAssistantStartsCheckBox.Checked)
                {
                    OpenFiverrInbox();
                }
            }

            UpdateActivityDashboard();
        }

        private void MainFormOnKeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F8)
            {
                _manualTalkCheckBox.Checked = !_manualTalkCheckBox.Checked;
                e.Handled = true;
                return;
            }

            if (e.KeyCode == Keys.F9)
            {
                ToggleSpeechHotkey();
                e.Handled = true;
            }
        }

        private void ToggleSpeechHotkey()
        {
            if (_manualTalkCheckBox.Checked)
            {
                Log("Manual talk takeover is active, so the speech hotkey will not speak.");
                SetStatus("Disable Manual talk takeover to use the bot voice.");
                UpdateActivityDashboard();
                return;
            }

            if (_speech.IsSpeaking)
            {
                _speech.Stop();
                Log("Speech stopped with F9.");
                SetStatus("Speech stopped.");
                UpdateActivityDashboard();
            }
            else
            {
                SpeakCurrentText();
            }
        }

        private void ApplyManualTalkMode()
        {
            var manualMode = _manualTalkCheckBox.Checked;

            if (manualMode)
            {
                _speech.Stop();
            }

            _speakButton.Enabled = !manualMode;
            _stopSpeechButton.Enabled = !manualMode;

            if (manualMode)
            {
                Log("Manual talk takeover enabled. Bot voice is paused so you can speak yourself.");
                SetStatus("Manual talk takeover is active.");
            }
            else
            {
                Log("Manual talk takeover disabled. Bot voice is available again.");
                SetStatus("Bot voice controls are available.");
            }

            UpdateActivityDashboard();
        }

        private void ScanTimerOnTick(object sender, EventArgs e)
        {
            AttemptAnswer(false);
        }

        private void ReplyTimerOnTick(object sender, EventArgs e)
        {
            ProcessReplyAssistantTick();
        }

        private void AttemptAnswer(bool manualRun)
        {
            if (_scanInProgress)
            {
                return;
            }

            _scanInProgress = true;
            try
            {
                var config = BuildAnswerConfig();
                var result = _callAutomation.TryAnswerIncomingCall(config);

                if (result.Answered)
                {
                    Log(string.Format(
                        "Answered call in \"{0}\" using button \"{1}\".",
                        result.TargetWindow,
                        result.ButtonName));
                    SetStatus("Incoming call answered.");
                }
                else if (manualRun)
                {
                    Log(result.Message);
                    SetStatus("Manual scan finished.");
                }
            }
            catch (Exception ex)
            {
                Log("Automation error: " + ex.Message);
                SetStatus("Automation error.");
            }
            finally
            {
                _scanInProgress = false;
            }
        }

        private void InspectButtons()
        {
            try
            {
                var config = BuildAnswerConfig();
                var matches = _callAutomation.InspectMatchingButtons(config);
                if (matches.Length == 0)
                {
                    Log("No buttons were discovered in the configured app windows.");
                    return;
                }

                Log("Discovered controls:");
                foreach (var match in matches.Take(25))
                {
                    Log("  " + match);
                }

                if (matches.Length > 25)
                {
                    Log("  ...");
                }
            }
            catch (Exception ex)
            {
                Log("Inspection error: " + ex.Message);
            }
        }

        private void SpeakCurrentText()
        {
            if (_manualTalkCheckBox.Checked)
            {
                Log("Bot speech is paused because manual talk takeover is active.");
                SetStatus("Disable manual talk takeover to let the bot speak again.");
                return;
            }

            try
            {
                _speech.Configure(
                    _voicesComboBox.SelectedItem as string,
                    _rateTrackBar.Value,
                    _volumeTrackBar.Value);
                _speech.SpeakAsync(_speechTextBox.Text);
                _learning.RememberPhrase(_speechTextBox.Text, "bot-speech");
                UpdateLearningSuggestions();
                Log("Speaking typed message.");
                SetStatus("Speaking through the default output device.");
                UpdateActivityDashboard();
            }
            catch (Exception ex)
            {
                Log("Speech error: " + ex.Message);
                SetStatus("Speech failed.");
                UpdateActivityDashboard();
            }
        }

        private void RememberCurrentPhrase(string source)
        {
            if (string.IsNullOrWhiteSpace(_speechTextBox.Text))
            {
                Log("Nothing to remember yet.");
                return;
            }

            _learning.RememberPhrase(_speechTextBox.Text, source);
            UpdateLearningSuggestions();
            Log("Saved the current phrase into local-only learning memory.");
        }

        private void UpdateLearningSuggestions()
        {
            var suggestions = _learning.GetSuggestions(_speechTextBox.Text, 8);
            _suggestionsListBox.BeginUpdate();
            try
            {
                _suggestionsListBox.Items.Clear();
                foreach (var suggestion in suggestions)
                {
                    _suggestionsListBox.Items.Add(suggestion);
                }
            }
            finally
            {
                _suggestionsListBox.EndUpdate();
            }
        }

        private void HideToTray(string balloonText)
        {
            ShowInTaskbar = false;
            Hide();

            if (!_trayBalloonShown)
            {
                _trayIcon.BalloonTipTitle = "Desk Call Assistant";
                _trayIcon.BalloonTipText = balloonText;
                _trayIcon.ShowBalloonTip(2000);
                _trayBalloonShown = true;
            }
        }

        private void RestoreFromTray()
        {
            Show();
            ShowInTaskbar = true;
            WindowState = FormWindowState.Normal;
            Activate();
        }

        private void ExitFromTray()
        {
            _forceExitFromTray = true;
            Close();
        }

        private void DetectFiverrMessage()
        {
            var snapshot = _fiverrAssistant.DetectInboxConversation();
            if (!snapshot.Found)
            {
                Log(snapshot.Message);
                SetStatus("Fiverr inbox was not detected.");
                return;
            }

            _fiverrIncomingMessageTextBox.Text = snapshot.LatestIncomingMessage;
            _fiverrStatusTextBox.Text = BuildFiverrStatus();
            Log("Read the visible Fiverr inbox content from the open browser window.");
            SetStatus("Fiverr inbox content detected.");
        }

        private void OpenFiverrInbox()
        {
            var opened = _fiverrAssistant.OpenInboxPage();
            if (opened)
            {
                Log("Opened the official Fiverr inbox page in the default browser.");
                SetStatus("Fiverr inbox page opened.");
            }
            else
            {
                Log("Failed to open the Fiverr inbox page automatically.");
                SetStatus("Could not open Fiverr inbox automatically.");
            }
        }

        private void GenerateFiverrReply()
        {
            var language = _fiverrLanguageComboBox.SelectedItem as string;
            var result = _fiverrAssistant.SuggestReply(_fiverrIncomingMessageTextBox.Text, language);
            _fiverrGeneratedReplyTextBox.Text = result.ReplyText;
            _fiverrStatusTextBox.Text = BuildFiverrStatus();
            Log(result.UsedFallback
                ? "Generated a fallback Fiverr draft because no learned Fiverr pattern matched yet."
                : "Generated a Fiverr draft from locally learned Fiverr message patterns.");
            SetStatus("Fiverr draft updated.");
        }

        private void LearnFiverrPair()
        {
            var language = _fiverrLanguageComboBox.SelectedItem as string;
            if (string.IsNullOrWhiteSpace(_fiverrIncomingMessageTextBox.Text) ||
                string.IsNullOrWhiteSpace(_fiverrGeneratedReplyTextBox.Text) ||
                string.IsNullOrWhiteSpace(language))
            {
                Log("Provide a Fiverr message, draft reply, and language before learning.");
                return;
            }

            _fiverrAssistant.RememberPair(
                _fiverrIncomingMessageTextBox.Text,
                _fiverrGeneratedReplyTextBox.Text,
                language);
            _fiverrStatusTextBox.Text = BuildFiverrStatus();
            Log("Saved the Fiverr reply pattern into external local storage.");
            SetStatus("Fiverr memory updated.");
        }

        private void DraftFiverrReply()
        {
            var result = _fiverrAssistant.DraftReply(_fiverrGeneratedReplyTextBox.Text);
            Log(result.Message);
            SetStatus(result.Message);
        }

        private void DetectCurrentMessage(bool manualRun)
        {
            MessagingPlatformDefinition platform;
            ConversationSnapshot snapshot;
            if (TryDetectConversationAcrossPlatforms(out platform, out snapshot))
            {
                _incomingMessageTextBox.Text = snapshot.LatestIncomingMessage;
                Log(string.Format(
                    "Detected chat on {0}: {1}",
                    platform != null ? platform.DisplayName : "unknown platform",
                    snapshot.WindowTitle));
                SetStatus("Latest message detected.");
            }
            else if (manualRun)
            {
                Log(snapshot.Message);
                SetStatus("No matching chat window detected.");
            }
        }

        private ReplySuggestionResult GenerateReplyFromCurrentInput(bool manualRun)
        {
            var platform = _replyPlatformComboBox.SelectedItem as MessagingPlatformDefinition;
            var language = _replyLanguageComboBox.SelectedItem as string;
            if (platform == null || string.IsNullOrWhiteSpace(language))
            {
                if (manualRun)
                {
                    Log("Select a platform and language first.");
                }

                return null;
            }

            var result = _replyLearning.SuggestReply(platform.Id, _incomingMessageTextBox.Text, language);
            _generatedReplyTextBox.Text = result.ReplyText;

            if (manualRun)
            {
                Log(result.UsedFallback
                    ? "Used the fallback reply because no learned message pattern matched yet."
                    : "Generated a reply from locally learned message patterns.");
                SetStatus("Reply suggestion updated.");
            }

            return result;
        }

        private void RememberCurrentReplyPair()
        {
            var platform = _replyPlatformComboBox.SelectedItem as MessagingPlatformDefinition;
            var language = _replyLanguageComboBox.SelectedItem as string;
            if (platform == null)
            {
                Log("Select a platform before learning a reply pattern.");
                return;
            }

            if (string.IsNullOrWhiteSpace(_incomingMessageTextBox.Text) ||
                string.IsNullOrWhiteSpace(_generatedReplyTextBox.Text) ||
                string.IsNullOrWhiteSpace(language))
            {
                Log("Provide an incoming message, a reply, and a language before learning.");
                return;
            }

            _replyLearning.RememberPair(
                platform.Id,
                _incomingMessageTextBox.Text,
                _generatedReplyTextBox.Text,
                language);
            Log("Learned a new local reply pattern.");
            SetStatus("Reply pattern saved locally.");
        }

        private void DraftCurrentReply()
        {
            var platform = _replyPlatformComboBox.SelectedItem as MessagingPlatformDefinition;
            if (platform == null)
            {
                Log("Select a platform before drafting a reply.");
                return;
            }

            var result = _messagingAutomation.DraftReply(platform, _generatedReplyTextBox.Text);
            Log(result.Message);
            SetStatus(result.Message);
        }

        private void SendCurrentReply()
        {
            var platform = _replyPlatformComboBox.SelectedItem as MessagingPlatformDefinition;
            var language = _replyLanguageComboBox.SelectedItem as string;
            if (platform == null)
            {
                Log("Select a platform before sending a reply.");
                return;
            }

            var result = _messagingAutomation.SendReply(platform, _generatedReplyTextBox.Text);
            Log(result.Message);
            SetStatus(result.Message);

            if (result.Found)
            {
                _replyLearning.RememberPair(
                    platform.Id,
                    _incomingMessageTextBox.Text,
                    _generatedReplyTextBox.Text,
                    language);
            }
        }

        private void ProcessReplyAssistantTick()
        {
            var language = _replyLanguageComboBox.SelectedItem as string;
            if (string.IsNullOrWhiteSpace(language))
            {
                return;
            }

            MessagingPlatformDefinition platform;
            ConversationSnapshot snapshot;
            if (!TryDetectConversationAcrossPlatforms(out platform, out snapshot) ||
                platform == null ||
                string.IsNullOrWhiteSpace(snapshot.LatestIncomingMessage))
            {
                return;
            }

            var replyKey = string.Format(
                "{0}|{1}|{2}",
                platform.Id,
                language,
                snapshot.LatestIncomingMessage.Trim());
            if (replyKey.Equals(_lastProcessedReplyKey, StringComparison.OrdinalIgnoreCase))
            {
                return;
            }

            _incomingMessageTextBox.Text = snapshot.LatestIncomingMessage;
            GenerateReplyFromCurrentInput(false);
            _lastProcessedReplyKey = replyKey;

            if (_autoSendReplyCheckBox.Checked)
            {
                SendCurrentReply();
            }
            else
            {
                DraftCurrentReply();
            }
        }

        private bool TryDetectConversationAcrossPlatforms(
            out MessagingPlatformDefinition matchedPlatform,
            out ConversationSnapshot matchedSnapshot)
        {
            matchedPlatform = null;
            matchedSnapshot = null;
            var fallbackSnapshot = new ConversationSnapshot
            {
                Found = false,
                Message = "No supported chat window was detected."
            };

            foreach (var platform in GetPreferredReplyPlatforms())
            {
                var snapshot = _messagingAutomation.DetectConversation(platform);
                if (snapshot.Found && !string.IsNullOrWhiteSpace(snapshot.LatestIncomingMessage))
                {
                    matchedPlatform = platform;
                    matchedSnapshot = snapshot;
                    SelectPlatformById(platform.Id);
                    return true;
                }

                if (!string.IsNullOrWhiteSpace(snapshot.Message))
                {
                    fallbackSnapshot = snapshot;
                }
            }

            matchedSnapshot = fallbackSnapshot;
            return false;
        }

        private MessagingPlatformDefinition[] GetPreferredReplyPlatforms()
        {
            var ordered = new List<MessagingPlatformDefinition>();
            var selectedPlatform = _replyPlatformComboBox.SelectedItem as MessagingPlatformDefinition;
            if (selectedPlatform != null)
            {
                ordered.Add(selectedPlatform);
            }

            for (var index = 0; index < _replyPlatformComboBox.Items.Count; index++)
            {
                var platform = _replyPlatformComboBox.Items[index] as MessagingPlatformDefinition;
                if (platform == null)
                {
                    continue;
                }

                if (selectedPlatform != null &&
                    platform.Id.Equals(selectedPlatform.Id, StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                ordered.Add(platform);
            }

            return ordered.ToArray();
        }

        private AnswerConfig BuildAnswerConfig()
        {
            return new AnswerConfig(
                _processNamesTextBox.Lines,
                _buttonLabelsTextBox.Lines);
        }

        private string GetSelectedPlatformId()
        {
            var platform = _replyPlatformComboBox.SelectedItem as MessagingPlatformDefinition;
            return platform != null ? platform.Id : string.Empty;
        }

        private void SelectPlatformById(string platformId)
        {
            if (string.IsNullOrWhiteSpace(platformId))
            {
                return;
            }

            for (var index = 0; index < _replyPlatformComboBox.Items.Count; index++)
            {
                var platform = _replyPlatformComboBox.Items[index] as MessagingPlatformDefinition;
                if (platform != null && platform.Id.Equals(platformId, StringComparison.OrdinalIgnoreCase))
                {
                    _replyPlatformComboBox.SelectedIndex = index;
                    return;
                }
            }
        }

        private static void SelectComboItemByText(ComboBox comboBox, string text)
        {
            if (comboBox == null || string.IsNullOrWhiteSpace(text))
            {
                return;
            }

            for (var index = 0; index < comboBox.Items.Count; index++)
            {
                var candidate = comboBox.Items[index] as string;
                if (candidate != null && candidate.Equals(text, StringComparison.OrdinalIgnoreCase))
                {
                    comboBox.SelectedIndex = index;
                    return;
                }
            }
        }

        private static int NormalizeInt(int value, int minimum, int maximum, int fallback)
        {
            if (value < minimum || value > maximum)
            {
                return fallback;
            }

            return value;
        }

        private static decimal NormalizeDecimal(decimal value, decimal minimum, decimal maximum, decimal fallback)
        {
            if (value < minimum || value > maximum)
            {
                return fallback;
            }

            return value;
        }

        private void Log(string message)
        {
            if (string.IsNullOrWhiteSpace(message))
            {
                return;
            }

            _logTextBox.AppendText(
                string.Format("[{0}] {1}{2}", DateTime.Now.ToString("HH:mm:ss"), message, Environment.NewLine));
        }

        private void SetStatus(string message)
        {
            _statusLabel.Text = message;
        }
    }
}
