// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

using System;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;

namespace DeskCallAssistant
{
    public sealed class MainForm : Form
    {
        private readonly CallAutomationService _callAutomation = new CallAutomationService();
        private readonly ComputePolicyService _computePolicy = new ComputePolicyService();
        private readonly LocalLearningService _learning = new LocalLearningService();
        private readonly SpeechService _speech = new SpeechService();
        private readonly Timer _scanTimer = new Timer();

        private readonly CheckBox _autoAnswerCheckBox = new CheckBox();
        private readonly CheckBox _manualTalkCheckBox = new CheckBox();
        private readonly CheckBox _preferGpuCheckBox = new CheckBox();
        private readonly NumericUpDown _scanIntervalSeconds = new NumericUpDown();
        private readonly TextBox _processNamesTextBox = new TextBox();
        private readonly TextBox _buttonLabelsTextBox = new TextBox();
        private readonly TextBox _computeStatusTextBox = new TextBox();
        private readonly TextBox _speechTextBox = new TextBox();
        private readonly ComboBox _voicesComboBox = new ComboBox();
        private readonly TrackBar _rateTrackBar = new TrackBar();
        private readonly TrackBar _volumeTrackBar = new TrackBar();
        private readonly TextBox _logTextBox = new TextBox();
        private readonly Button _scanNowButton = new Button();
        private readonly Button _inspectButtonsButton = new Button();
        private readonly Button _rememberPhraseButton = new Button();
        private readonly Button _speakButton = new Button();
        private readonly Button _stopSpeechButton = new Button();
        private readonly ListBox _suggestionsListBox = new ListBox();
        private readonly Label _statusLabel = new Label();

        private bool _scanInProgress;

        public MainForm()
        {
            Text = "Desk Call Assistant";
            StartPosition = FormStartPosition.CenterScreen;
            MinimumSize = new Size(980, 720);
            ClientSize = new Size(980, 720);
            KeyPreview = true;

            InitializeLayout();
            LoadVoices();

            _scanTimer.Tick += ScanTimerOnTick;
            KeyDown += MainFormOnKeyDown;
            UpdateTimerState();
            Log("Ready. Configure process names and button labels, then enable Auto-answer.");
        }

        protected override void OnFormClosed(FormClosedEventArgs e)
        {
            _scanTimer.Stop();
            _speech.Dispose();
            base.OnFormClosed(e);
        }

        private void InitializeLayout()
        {
            var root = new TableLayoutPanel
            {
                Dock = DockStyle.Fill,
                Padding = new Padding(12),
                ColumnCount = 1,
                RowCount = 5
            };
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 180f));
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 130f));
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 320f));
            root.RowStyles.Add(new RowStyle(SizeType.Percent, 100f));
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 34f));
            Controls.Add(root);

            root.Controls.Add(BuildAutomationPanel(), 0, 0);
            root.Controls.Add(BuildComputePanel(), 0, 1);
            root.Controls.Add(BuildSpeechPanel(), 0, 2);
            root.Controls.Add(BuildLogPanel(), 0, 3);
            root.Controls.Add(BuildStatusPanel(), 0, 4);
        }

        private Control BuildAutomationPanel()
        {
            var group = new GroupBox
            {
                Text = "Auto-answer setup",
                Dock = DockStyle.Fill
            };

            var layout = new TableLayoutPanel
            {
                Dock = DockStyle.Fill,
                Padding = new Padding(10),
                ColumnCount = 4,
                RowCount = 3
            };
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 180f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 180f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36f));
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 42f));

            _autoAnswerCheckBox.Text = "Enable auto-answer";
            _autoAnswerCheckBox.Dock = DockStyle.Fill;
            _autoAnswerCheckBox.CheckedChanged += (_, __) => UpdateTimerState();

            _scanIntervalSeconds.Minimum = 1;
            _scanIntervalSeconds.Maximum = 30;
            _scanIntervalSeconds.Value = 2;
            _scanIntervalSeconds.Dock = DockStyle.Left;
            _scanIntervalSeconds.Width = 80;
            _scanIntervalSeconds.ValueChanged += (_, __) => UpdateTimerState();

            var intervalPanel = new FlowLayoutPanel
            {
                Dock = DockStyle.Fill,
                FlowDirection = FlowDirection.LeftToRight,
                WrapContents = false
            };
            intervalPanel.Controls.Add(new Label
            {
                Text = "Scan every",
                AutoSize = true,
                TextAlign = ContentAlignment.MiddleLeft,
                Padding = new Padding(0, 7, 0, 0)
            });
            intervalPanel.Controls.Add(_scanIntervalSeconds);
            intervalPanel.Controls.Add(new Label
            {
                Text = "seconds",
                AutoSize = true,
                TextAlign = ContentAlignment.MiddleLeft,
                Padding = new Padding(0, 7, 0, 0)
            });

            _processNamesTextBox.Multiline = true;
            _processNamesTextBox.ScrollBars = ScrollBars.Vertical;
            _processNamesTextBox.Dock = DockStyle.Fill;
            _processNamesTextBox.Text = "chrome\r\nmsedge\r\nWhatsApp\r\nMessenger";

            _buttonLabelsTextBox.Multiline = true;
            _buttonLabelsTextBox.ScrollBars = ScrollBars.Vertical;
            _buttonLabelsTextBox.Dock = DockStyle.Fill;
            _buttonLabelsTextBox.Text = "Answer\r\nAccept\r\nPick up\r\nJoin";

            _scanNowButton.Text = "Scan and answer now";
            _scanNowButton.AutoSize = true;
            _scanNowButton.Click += (_, __) => AttemptAnswer(manualRun: true);

            _inspectButtonsButton.Text = "Inspect matching buttons";
            _inspectButtonsButton.AutoSize = true;
            _inspectButtonsButton.Click += (_, __) => InspectButtons();

            var actionsPanel = new FlowLayoutPanel
            {
                Dock = DockStyle.Fill,
                FlowDirection = FlowDirection.LeftToRight
            };
            actionsPanel.Controls.Add(_scanNowButton);
            actionsPanel.Controls.Add(_inspectButtonsButton);

            layout.Controls.Add(_autoAnswerCheckBox, 0, 0);
            layout.SetColumnSpan(_autoAnswerCheckBox, 2);
            layout.Controls.Add(intervalPanel, 2, 0);
            layout.SetColumnSpan(intervalPanel, 2);

            layout.Controls.Add(new Label
            {
                Text = "Target process names\r\n(one per line)",
                AutoSize = true,
                Dock = DockStyle.Fill
            }, 0, 1);
            layout.Controls.Add(_processNamesTextBox, 1, 1);
            layout.Controls.Add(new Label
            {
                Text = "Answer button labels\r\n(one per line)",
                AutoSize = true,
                Dock = DockStyle.Fill
            }, 2, 1);
            layout.Controls.Add(_buttonLabelsTextBox, 3, 1);
            layout.Controls.Add(actionsPanel, 0, 2);
            layout.SetColumnSpan(actionsPanel, 4);

            group.Controls.Add(layout);
            return group;
        }

        private Control BuildComputePanel()
        {
            var group = new GroupBox
            {
                Text = "Compute policy",
                Dock = DockStyle.Fill
            };

            var layout = new TableLayoutPanel
            {
                Dock = DockStyle.Fill,
                Padding = new Padding(10),
                ColumnCount = 1,
                RowCount = 2
            };
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34f));
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100f));

            _preferGpuCheckBox.Text = "Prefer GPU for local bot workloads";
            _preferGpuCheckBox.AutoSize = true;
            _preferGpuCheckBox.CheckedChanged += (_, __) =>
            {
                UpdateComputeStatus();
                Log(_preferGpuCheckBox.Checked
                    ? "GPU preference enabled for local bot workloads."
                    : "GPU preference disabled for local bot workloads.");
            };

            _computeStatusTextBox.Multiline = true;
            _computeStatusTextBox.ReadOnly = true;
            _computeStatusTextBox.ScrollBars = ScrollBars.Vertical;
            _computeStatusTextBox.Dock = DockStyle.Fill;
            _computeStatusTextBox.BackColor = Color.White;

            layout.Controls.Add(_preferGpuCheckBox, 0, 0);
            layout.Controls.Add(_computeStatusTextBox, 0, 1);
            group.Controls.Add(layout);

            UpdateComputeStatus();
            return group;
        }

        private Control BuildSpeechPanel()
        {
            var group = new GroupBox
            {
                Text = "Typed speech",
                Dock = DockStyle.Fill
            };

            var layout = new TableLayoutPanel
            {
                Dock = DockStyle.Fill,
                Padding = new Padding(10),
                ColumnCount = 4,
                RowCount = 6
            };
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 120f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 120f));
            layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 120f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 90f));
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100f));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 44f));

            _manualTalkCheckBox.Text = "Manual talk takeover (F8)";
            _manualTalkCheckBox.AutoSize = true;
            _manualTalkCheckBox.CheckedChanged += (_, __) => ApplyManualTalkMode();

            _voicesComboBox.Dock = DockStyle.Fill;
            _voicesComboBox.DropDownStyle = ComboBoxStyle.DropDownList;

            _rateTrackBar.Dock = DockStyle.Fill;
            _rateTrackBar.Minimum = -5;
            _rateTrackBar.Maximum = 5;
            _rateTrackBar.TickFrequency = 1;

            _volumeTrackBar.Dock = DockStyle.Fill;
            _volumeTrackBar.Minimum = 0;
            _volumeTrackBar.Maximum = 100;
            _volumeTrackBar.TickFrequency = 10;
            _volumeTrackBar.Value = 100;

            _speechTextBox.Multiline = true;
            _speechTextBox.ScrollBars = ScrollBars.Vertical;
            _speechTextBox.Dock = DockStyle.Fill;
            _speechTextBox.Text = "Hello, please give me a moment.";
            _speechTextBox.TextChanged += (_, __) => UpdateLearningSuggestions();

            _speakButton.Text = "Speak";
            _speakButton.Dock = DockStyle.Fill;
            _speakButton.Click += (_, __) => SpeakCurrentText();

            _rememberPhraseButton.Text = "Remember";
            _rememberPhraseButton.Dock = DockStyle.Fill;
            _rememberPhraseButton.Click += (_, __) => RememberCurrentPhrase("manual-save");

            _stopSpeechButton.Text = "Stop";
            _stopSpeechButton.Dock = DockStyle.Fill;
            _stopSpeechButton.Click += (_, __) =>
            {
                _speech.Stop();
                Log("Speech stopped.");
            };

            _suggestionsListBox.Dock = DockStyle.Fill;
            _suggestionsListBox.DoubleClick += (_, __) =>
            {
                if (_suggestionsListBox.SelectedItem == null)
                {
                    return;
                }

                _speechTextBox.Text = _suggestionsListBox.SelectedItem.ToString();
                _speechTextBox.SelectionStart = _speechTextBox.TextLength;
            };

            layout.Controls.Add(_manualTalkCheckBox, 0, 0);
            layout.SetColumnSpan(_manualTalkCheckBox, 2);
            layout.Controls.Add(new Label
            {
                Text = "When enabled, the bot stops speaking so you can use your own microphone.",
                AutoSize = true,
                Dock = DockStyle.Fill
            }, 2, 0);
            layout.SetColumnSpan(layout.GetControlFromPosition(2, 0), 2);

            layout.Controls.Add(new Label { Text = "Voice", AutoSize = true, TextAlign = ContentAlignment.MiddleLeft }, 0, 1);
            layout.Controls.Add(_voicesComboBox, 1, 1);
            layout.Controls.Add(new Label { Text = "Rate", AutoSize = true, TextAlign = ContentAlignment.MiddleLeft }, 2, 1);
            layout.Controls.Add(_rateTrackBar, 3, 1);

            layout.Controls.Add(new Label { Text = "Volume", AutoSize = true, TextAlign = ContentAlignment.MiddleLeft }, 0, 2);
            layout.Controls.Add(_volumeTrackBar, 1, 2);
            layout.Controls.Add(new Label
            {
                Text = "Tip: this app speaks to your default speaker. For clean in-call audio, route your speaker output into a virtual microphone.",
                AutoSize = true,
                Dock = DockStyle.Fill
            }, 2, 2);
            layout.SetColumnSpan(layout.GetControlFromPosition(2, 2), 2);

            layout.Controls.Add(new Label { Text = "Type what should be spoken", AutoSize = true, Dock = DockStyle.Fill }, 0, 3);
            layout.Controls.Add(_speechTextBox, 1, 3);
            layout.SetColumnSpan(_speechTextBox, 3);

            layout.Controls.Add(new Label { Text = "Local suggestions", AutoSize = true, Dock = DockStyle.Fill }, 0, 4);
            layout.Controls.Add(_suggestionsListBox, 1, 4);
            layout.SetColumnSpan(_suggestionsListBox, 3);

            var actionPanel = new TableLayoutPanel
            {
                Dock = DockStyle.Fill,
                ColumnCount = 3,
                RowCount = 1
            };
            actionPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33f));
            actionPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33f));
            actionPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.34f));
            actionPanel.Controls.Add(_rememberPhraseButton, 0, 0);
            actionPanel.Controls.Add(_speakButton, 1, 0);
            actionPanel.Controls.Add(_stopSpeechButton, 2, 0);
            layout.Controls.Add(actionPanel, 1, 5);
            layout.SetColumnSpan(actionPanel, 3);

            group.Controls.Add(layout);
            return group;
        }

        private Control BuildLogPanel()
        {
            var group = new GroupBox
            {
                Text = "Activity log",
                Dock = DockStyle.Fill
            };

            _logTextBox.Multiline = true;
            _logTextBox.ReadOnly = true;
            _logTextBox.ScrollBars = ScrollBars.Vertical;
            _logTextBox.Dock = DockStyle.Fill;
            _logTextBox.BackColor = Color.White;

            group.Controls.Add(_logTextBox);
            return group;
        }

        private Control BuildStatusPanel()
        {
            _statusLabel.Dock = DockStyle.Fill;
            _statusLabel.TextAlign = ContentAlignment.MiddleLeft;
            return _statusLabel;
        }

        private void LoadVoices()
        {
            var voices = _speech.GetInstalledVoices();
            foreach (var voice in voices)
            {
                _voicesComboBox.Items.Add(voice);
            }

            if (_voicesComboBox.Items.Count > 0)
            {
                _voicesComboBox.SelectedIndex = 0;
            }

            UpdateLearningSuggestions();
        }

        private void UpdateComputeStatus()
        {
            var status = _computePolicy.GetStatus(_preferGpuCheckBox.Checked);
            _computeStatusTextBox.Text = string.Format(
                "{0}{1}{1}{2}",
                status.Summary,
                Environment.NewLine,
                AppPolicy.BuildPrivacySummary(_learning.StoragePath));
        }

        private void MainFormOnKeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode != Keys.F8)
            {
                return;
            }

            _manualTalkCheckBox.Checked = !_manualTalkCheckBox.Checked;
            e.Handled = true;
        }

        private void ApplyManualTalkMode()
        {
            var manualMode = _manualTalkCheckBox.Checked;

            if (manualMode)
            {
                _speech.Stop();
            }

            _speakButton.Enabled = !manualMode;
            _stopSpeechButton.Enabled = !manualMode;

            if (manualMode)
            {
                Log("Manual talk takeover enabled. Bot voice is paused so you can speak yourself.");
                SetStatus("Manual talk takeover is active.");
            }
            else
            {
                Log("Manual talk takeover disabled. Bot voice is available again.");
                SetStatus("Bot voice controls are available.");
            }
        }

        private void UpdateTimerState()
        {
            _scanTimer.Stop();

            if (_autoAnswerCheckBox.Checked)
            {
                _scanTimer.Interval = (int)_scanIntervalSeconds.Value * 1000;
                _scanTimer.Start();
                SetStatus("Auto-answer is watching for incoming call buttons.");
            }
            else
            {
                SetStatus("Auto-answer is paused.");
            }
        }

        private void ScanTimerOnTick(object sender, EventArgs e)
        {
            AttemptAnswer(manualRun: false);
        }

        private void AttemptAnswer(bool manualRun)
        {
            if (_scanInProgress)
            {
                return;
            }

            _scanInProgress = true;
            try
            {
                var config = BuildAnswerConfig();
                var result = _callAutomation.TryAnswerIncomingCall(config);

                if (result.Answered)
                {
                    Log(string.Format(
                        "Answered call in \"{0}\" using button \"{1}\".",
                        result.TargetWindow,
                        result.ButtonName));
                    SetStatus("Incoming call answered.");
                }
                else if (manualRun)
                {
                    Log(result.Message);
                    SetStatus("Manual scan finished.");
                }
            }
            catch (Exception ex)
            {
                Log("Automation error: " + ex.Message);
                SetStatus("Automation error.");
            }
            finally
            {
                _scanInProgress = false;
            }
        }

        private void InspectButtons()
        {
            try
            {
                var config = BuildAnswerConfig();
                var matches = _callAutomation.InspectMatchingButtons(config);
                if (matches.Length == 0)
                {
                    Log("No buttons were discovered in the configured app windows.");
                    return;
                }

                Log("Discovered controls:");
                foreach (var match in matches.Take(25))
                {
                    Log("  " + match);
                }

                if (matches.Length > 25)
                {
                    Log("  ...");
                }
            }
            catch (Exception ex)
            {
                Log("Inspection error: " + ex.Message);
            }
        }

        private void SpeakCurrentText()
        {
            if (_manualTalkCheckBox.Checked)
            {
                Log("Bot speech is paused because manual talk takeover is active.");
                SetStatus("Disable manual talk takeover to let the bot speak again.");
                return;
            }

            try
            {
                _speech.Configure(
                    _voicesComboBox.SelectedItem as string,
                    _rateTrackBar.Value,
                    _volumeTrackBar.Value);
                _speech.SpeakAsync(_speechTextBox.Text);
                _learning.RememberPhrase(_speechTextBox.Text, "bot-speech");
                UpdateLearningSuggestions();
                Log("Speaking typed message.");
                SetStatus("Speaking through the default output device.");
            }
            catch (Exception ex)
            {
                Log("Speech error: " + ex.Message);
                SetStatus("Speech failed.");
            }
        }

        private void RememberCurrentPhrase(string source)
        {
            if (string.IsNullOrWhiteSpace(_speechTextBox.Text))
            {
                Log("Nothing to remember yet.");
                return;
            }

            _learning.RememberPhrase(_speechTextBox.Text, source);
            UpdateLearningSuggestions();
            Log("Saved the current phrase into local-only learning memory.");
        }

        private void UpdateLearningSuggestions()
        {
            var suggestions = _learning.GetSuggestions(_speechTextBox.Text, 8);
            _suggestionsListBox.BeginUpdate();
            try
            {
                _suggestionsListBox.Items.Clear();
                foreach (var suggestion in suggestions)
                {
                    _suggestionsListBox.Items.Add(suggestion);
                }
            }
            finally
            {
                _suggestionsListBox.EndUpdate();
            }
        }

        private AnswerConfig BuildAnswerConfig()
        {
            return new AnswerConfig(
                _processNamesTextBox.Lines,
                _buttonLabelsTextBox.Lines);
        }

        private void Log(string message)
        {
            if (string.IsNullOrWhiteSpace(message))
            {
                return;
            }

            _logTextBox.AppendText(
                string.Format("[{0}] {1}{2}", DateTime.Now.ToString("HH:mm:ss"), message, Environment.NewLine));
        }

        private void SetStatus(string message)
        {
            _statusLabel.Text = message;
        }
    }
}
