// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace DeskCallAssistant
{
    public sealed class MessagingReplyLearningService
    {
        private sealed class ReplyPatternRecord
        {
            public string PlatformId { get; set; }

            public string Language { get; set; }

            public string IncomingText { get; set; }

            public string ReplyText { get; set; }

            public int Count { get; set; }

            public long LastUsedUtcTicks { get; set; }
        }

        private readonly string _storagePath;

        public MessagingReplyLearningService()
        {
            var root = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                "DeskCallAssistant");
            Directory.CreateDirectory(root);
            _storagePath = Path.Combine(root, "ReplyPatterns.tsv");
        }

        public MessagingReplyLearningService(string storagePath)
        {
            if (string.IsNullOrWhiteSpace(storagePath))
            {
                throw new ArgumentException("storagePath");
            }

            var directory = Path.GetDirectoryName(storagePath);
            if (!string.IsNullOrWhiteSpace(directory))
            {
                Directory.CreateDirectory(directory);
            }

            _storagePath = storagePath;
        }

        public string StoragePath
        {
            get { return _storagePath; }
        }

        public void RememberPair(string platformId, string incomingText, string replyText, string language)
        {
            AppPolicy.EnsureLocalOnlyLearning();

            var normalizedIncoming = Normalize(incomingText);
            var normalizedReply = Normalize(replyText);
            var normalizedPlatform = Normalize(platformId);
            var normalizedLanguage = Normalize(language);

            if (string.IsNullOrWhiteSpace(normalizedIncoming) ||
                string.IsNullOrWhiteSpace(normalizedReply) ||
                string.IsNullOrWhiteSpace(normalizedPlatform) ||
                string.IsNullOrWhiteSpace(normalizedLanguage))
            {
                return;
            }

            var records = LoadRecords();
            var key = BuildKey(normalizedPlatform, normalizedLanguage, normalizedIncoming, normalizedReply);

            ReplyPatternRecord record;
            if (!records.TryGetValue(key, out record))
            {
                record = new ReplyPatternRecord
                {
                    PlatformId = normalizedPlatform,
                    Language = normalizedLanguage,
                    IncomingText = normalizedIncoming,
                    ReplyText = normalizedReply,
                    Count = 0
                };
                records[key] = record;
            }

            record.Count += 1;
            record.LastUsedUtcTicks = DateTime.UtcNow.Ticks;

            SaveRecords(records.Values);
        }

        public ReplySuggestionResult SuggestReply(string platformId, string incomingText, string language)
        {
            AppPolicy.EnsureLocalOnlyLearning();

            var normalizedIncoming = Normalize(incomingText);
            var normalizedPlatform = Normalize(platformId);
            var normalizedLanguage = Normalize(language);
            var records = LoadRecords().Values;

            var bestMatch = records
                .Where(item => item.PlatformId.Equals(normalizedPlatform, StringComparison.OrdinalIgnoreCase))
                .Where(item => item.Language.Equals(normalizedLanguage, StringComparison.OrdinalIgnoreCase))
                .Select(item => new
                {
                    Record = item,
                    Score = Score(item.IncomingText, normalizedIncoming) + item.Count
                })
                .Where(item => item.Score > 0)
                .OrderByDescending(item => item.Score)
                .ThenByDescending(item => item.Record.Count)
                .ThenByDescending(item => item.Record.LastUsedUtcTicks)
                .FirstOrDefault();

            if (bestMatch != null)
            {
                return new ReplySuggestionResult
                {
                    ReplyText = bestMatch.Record.ReplyText,
                    Score = bestMatch.Score,
                    UsedFallback = false,
                    Language = normalizedLanguage,
                    PlatformId = normalizedPlatform
                };
            }

            return new ReplySuggestionResult
            {
                ReplyText = BuildFallbackReply(normalizedLanguage),
                Score = 0,
                UsedFallback = true,
                Language = normalizedLanguage,
                PlatformId = normalizedPlatform
            };
        }

        private Dictionary<string, ReplyPatternRecord> LoadRecords()
        {
            var results = new Dictionary<string, ReplyPatternRecord>(StringComparer.OrdinalIgnoreCase);

            if (!File.Exists(_storagePath))
            {
                return results;
            }

            foreach (var line in File.ReadAllLines(_storagePath))
            {
                if (string.IsNullOrWhiteSpace(line))
                {
                    continue;
                }

                var parts = line.Split('\t');
                if (parts.Length < 6)
                {
                    continue;
                }

                int count;
                long ticks;
                if (!int.TryParse(parts[4], out count))
                {
                    count = 0;
                }

                if (!long.TryParse(parts[5], out ticks))
                {
                    ticks = 0;
                }

                var record = new ReplyPatternRecord
                {
                    PlatformId = Normalize(parts[0]),
                    Language = Normalize(parts[1]),
                    IncomingText = Normalize(parts[2]),
                    ReplyText = Normalize(parts[3]),
                    Count = count,
                    LastUsedUtcTicks = ticks
                };

                if (string.IsNullOrWhiteSpace(record.PlatformId) ||
                    string.IsNullOrWhiteSpace(record.Language) ||
                    string.IsNullOrWhiteSpace(record.IncomingText) ||
                    string.IsNullOrWhiteSpace(record.ReplyText))
                {
                    continue;
                }

                results[BuildKey(record.PlatformId, record.Language, record.IncomingText, record.ReplyText)] = record;
            }

            return results;
        }

        private void SaveRecords(IEnumerable<ReplyPatternRecord> records)
        {
            var lines = records
                .OrderBy(item => item.PlatformId)
                .ThenBy(item => item.Language)
                .ThenByDescending(item => item.Count)
                .Select(item => string.Format(
                    "{0}\t{1}\t{2}\t{3}\t{4}\t{5}",
                    Normalize(item.PlatformId),
                    Normalize(item.Language),
                    Normalize(item.IncomingText),
                    Normalize(item.ReplyText),
                    item.Count,
                    item.LastUsedUtcTicks))
                .ToArray();

            File.WriteAllLines(_storagePath, lines);
        }

        private static string BuildKey(string platformId, string language, string incomingText, string replyText)
        {
            return string.Join("|", new[]
            {
                Normalize(platformId).ToLowerInvariant(),
                Normalize(language).ToLowerInvariant(),
                Normalize(incomingText).ToLowerInvariant(),
                Normalize(replyText).ToLowerInvariant()
            });
        }

        private static int Score(string storedIncoming, string liveIncoming)
        {
            if (string.IsNullOrWhiteSpace(storedIncoming) || string.IsNullOrWhiteSpace(liveIncoming))
            {
                return 0;
            }

            if (storedIncoming.Equals(liveIncoming, StringComparison.OrdinalIgnoreCase))
            {
                return 1000;
            }

            if (storedIncoming.StartsWith(liveIncoming, StringComparison.OrdinalIgnoreCase) ||
                liveIncoming.StartsWith(storedIncoming, StringComparison.OrdinalIgnoreCase))
            {
                return 800;
            }

            if (storedIncoming.IndexOf(liveIncoming, StringComparison.OrdinalIgnoreCase) >= 0 ||
                liveIncoming.IndexOf(storedIncoming, StringComparison.OrdinalIgnoreCase) >= 0)
            {
                return 500;
            }

            var score = 0;
            foreach (var token in liveIncoming.Split(' '))
            {
                if (token.Length < 2)
                {
                    continue;
                }

                if (storedIncoming.IndexOf(token, StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    score += 100;
                }
            }

            return score;
        }

        private static string BuildFallbackReply(string language)
        {
            var normalized = Normalize(language).ToLowerInvariant();
            if (normalized == "bengali")
            {
                return "আসসালামু আলাইকুম। বার্তাটির জন্য ধন্যবাদ, একটু পর বিস্তারিত জানাচ্ছি।";
            }

            if (normalized == "japanese")
            {
                return "こんにちは。メッセージありがとうございます。後ほど詳しく返信します。";
            }

            if (normalized == "banglish")
            {
                return "Assalamu alaikum, message er jonno dhonnobad. Ektu pore details diye reply dicchi.";
            }

            return "Hello, thanks for your message. I'll reply in more detail shortly.";
        }

        private static string Normalize(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return string.Empty;
            }

            return value
                .Replace('\r', ' ')
                .Replace('\n', ' ')
                .Replace('\t', ' ')
                .Trim();
        }
    }
}
