// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

namespace DeskCallAssistant
{
    public sealed class MessagingPlatformDefinition
    {
        public string Id { get; set; }

        public string DisplayName { get; set; }

        public string[] ProcessNames { get; set; }

        public string[] WindowTitleHints { get; set; }

        public override string ToString()
        {
            return DisplayName ?? base.ToString();
        }
    }
}
