// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.
// Independent implementation note:
// The platform-specific detection heuristics in this file were refined after reviewing
// public reference repositories by Benojir, sajidmahamud835, NishDoitAll, and
// o-x-y-g-e-n. Their projects were used as inspiration for platform coverage and
// detection strategy ideas only; this C# implementation was written independently
// for this Windows desktop app and does not copy their source code.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading;
using System.Windows.Automation;
using System.Windows.Forms;

namespace DeskCallAssistant
{
    public sealed class MessagingAutomationService
    {
        private DateTime _lastWhatsAppDirectActivationUtc = DateTime.MinValue;

        public MessagingPlatformDefinition[] GetSupportedPlatforms()
        {
            return new[]
            {
                new MessagingPlatformDefinition
                {
                    Id = "whatsapp",
                    DisplayName = "WhatsApp",
                    ProcessNames = new[] { "WhatsApp", "ApplicationFrameHost", "chrome", "msedge" },
                    WindowTitleHints = new[] { "WhatsApp", "Chats", "Status" }
                },
                new MessagingPlatformDefinition
                {
                    Id = "telegram",
                    DisplayName = "Telegram / Unigram",
                    ProcessNames = new[] { "Telegram", "Unigram", "ApplicationFrameHost", "chrome", "msedge" },
                    WindowTitleHints = new[] { "Telegram", "Unigram", "Chats" }
                },
                new MessagingPlatformDefinition
                {
                    Id = "messenger",
                    DisplayName = "Messenger",
                    ProcessNames = new[] { "Messenger", "chrome", "msedge" },
                    WindowTitleHints = new[] { "Messenger", "messenger.com", "facebook" }
                },
                new MessagingPlatformDefinition
                {
                    Id = "facebook-messages",
                    DisplayName = "Facebook Messages",
                    ProcessNames = new[] { "chrome", "msedge" },
                    WindowTitleHints = new[] { "Facebook", "Messenger", "Inbox", "facebook.com", "Messages" }
                }
            };
        }

        public ConversationSnapshot DetectConversation(MessagingPlatformDefinition platform)
        {
            return DetectConversation(platform, true);
        }

        public ConversationSnapshot DetectConversation(MessagingPlatformDefinition platform, bool autoSelectChat)
        {
            if (platform == null)
            {
                return new ConversationSnapshot
                {
                    Found = false,
                    Message = "Select a platform first."
                };
            }

            var desktop = AutomationElement.RootElement;
            var windows = desktop.FindAll(TreeScope.Children, Condition.TrueCondition);
            var lastMessage = string.Empty;

            foreach (AutomationElement window in windows)
            {
                if (!MatchesWindow(window, platform))
                {
                    continue;
                }

                var snapshot = BuildPlatformSnapshot(platform, window, autoSelectChat);
                if (snapshot.Found)
                {
                    return snapshot;
                }

                if (!string.IsNullOrWhiteSpace(snapshot.Message))
                {
                    lastMessage = snapshot.Message;
                }
            }

            return new ConversationSnapshot
            {
                Found = false,
                PlatformId = platform.Id,
                Message = !string.IsNullOrWhiteSpace(lastMessage)
                    ? lastMessage
                    : "No matching chat window was found for the selected platform."
            };
        }

        public ConversationSnapshot DraftReply(MessagingPlatformDefinition platform, string replyText)
        {
            return DraftReply(platform, replyText, true);
        }

        public ConversationSnapshot DraftReply(MessagingPlatformDefinition platform, string replyText, bool autoSelectChat)
        {
            var snapshot = DetectConversation(platform, autoSelectChat);
            if (!snapshot.Found && IsWhatsAppPlatform(platform) && HasRecentWhatsAppDirectActivation())
            {
                var activeWhatsAppWindow = FindBestWindow(platform);
                if (activeWhatsAppWindow != null)
                {
                    snapshot = BuildSnapshot(platform, activeWhatsAppWindow);
                    if (snapshot.ComposerFound)
                    {
                        snapshot.Found = true;
                        snapshot.Message = "Using the open WhatsApp direct chat that unread detection already selected.";
                    }
                }
            }

            if (!snapshot.Found)
            {
                return snapshot;
            }

            var window = FindBestWindow(platform);
            if (window == null)
            {
                snapshot.Message = "The chat window disappeared before the reply could be drafted.";
                snapshot.Found = false;
                return snapshot;
            }

            var composer = FindComposer(window, platform);
            if (composer == null)
            {
                snapshot.Message = "The chat composer could not be found.";
                snapshot.Found = false;
                return snapshot;
            }

            if (TrySetComposerText(composer, replyText))
            {
                snapshot.Message = "Drafted the reply into the active chat composer.";
                return snapshot;
            }

            snapshot.Message = "Found the chat, but failed to draft the reply into the composer.";
            snapshot.Found = false;
            return snapshot;
        }

        public ConversationSnapshot SendReply(MessagingPlatformDefinition platform, string replyText)
        {
            return SendReply(platform, replyText, true);
        }

        public ConversationSnapshot SendReply(MessagingPlatformDefinition platform, string replyText, bool autoSelectChat)
        {
            var drafted = DraftReply(platform, replyText, autoSelectChat);
            if (!drafted.Found)
            {
                return drafted;
            }

            var window = FindBestWindow(platform);
            if (window == null)
            {
                drafted.Message = "The chat window disappeared before send could be attempted.";
                drafted.Found = false;
                return drafted;
            }

            var sendButton = FindSendButton(window, platform);
            if (sendButton != null && TryInvoke(sendButton))
            {
                drafted.Message = "Sent the drafted reply.";
                return drafted;
            }

            try
            {
                window.SetFocus();
                SendKeys.SendWait("{ENTER}");
                drafted.Message = "Sent the drafted reply using the Enter key.";
                return drafted;
            }
            catch
            {
                drafted.Found = false;
                drafted.Message = "Failed to send the reply automatically.";
                return drafted;
            }
        }

        private ConversationSnapshot BuildPlatformSnapshot(
            MessagingPlatformDefinition platform,
            AutomationElement window,
            bool autoSelectChat)
        {
            if (IsWhatsAppPlatform(platform))
            {
                return BuildWhatsAppConversationSnapshot(platform, window, autoSelectChat);
            }

            if (IsMessengerFamilyPlatform(platform))
            {
                return BuildMessengerConversationSnapshot(platform, window, autoSelectChat);
            }

            if (IsTelegramPlatform(platform))
            {
                return BuildBrowserConversationSnapshot(
                    platform,
                    window,
                    autoSelectChat,
                    "Telegram or Unigram chat detected.");
            }

            return BuildSnapshot(platform, window);
        }

        private AutomationElement FindBestWindow(MessagingPlatformDefinition platform)
        {
            var desktop = AutomationElement.RootElement;
            var windows = desktop.FindAll(TreeScope.Children, Condition.TrueCondition);
            foreach (AutomationElement window in windows)
            {
                if (MatchesWindow(window, platform))
                {
                    return window;
                }
            }

            return null;
        }

        private ConversationSnapshot BuildWhatsAppConversationSnapshot(
            MessagingPlatformDefinition platform,
            AutomationElement window,
            bool autoSelectChat)
        {
            var unreadSnapshot = autoSelectChat
                ? BuildWhatsAppUnreadSnapshot(platform, window)
                : BuildNotAutoSelectingSnapshot(platform, window, "WhatsApp auto-select is disabled, so the currently open chat is used only.");
            if (unreadSnapshot.Found)
            {
                return unreadSnapshot;
            }

            var activeSnapshot = BuildSnapshot(platform, window);
            if (activeSnapshot.ComposerFound &&
                !string.IsNullOrWhiteSpace(activeSnapshot.LatestIncomingMessage))
            {
                activeSnapshot.Message = "Detected the open WhatsApp chat.";
                return activeSnapshot;
            }

            if (activeSnapshot.ComposerFound)
            {
                activeSnapshot.Found = false;
                activeSnapshot.Message = "WhatsApp is open, but no readable incoming message was detected yet.";
                return activeSnapshot;
            }

            return unreadSnapshot;
        }

        private ConversationSnapshot BuildWhatsAppUnreadSnapshot(
            MessagingPlatformDefinition platform,
            AutomationElement window)
        {
            var unreadCandidates = FindWhatsAppUnreadChatCandidates(window);
            var directCandidates = unreadCandidates
                .Where(candidate => !IsLikelyWhatsAppGroupRow(candidate))
                .ToArray();

            if (directCandidates.Length == 0)
            {
                return new ConversationSnapshot
                {
                    Found = false,
                    PlatformId = platform.Id,
                    WindowTitle = SafeName(window),
                    Message = unreadCandidates.Length == 0
                        ? "No unread direct WhatsApp chats were detected."
                        : "Unread WhatsApp chats were found, but they look like group conversations."
                };
            }

            foreach (var candidate in directCandidates)
            {
                if (!TryActivateChat(candidate))
                {
                    continue;
                }

                Thread.Sleep(180);

                var snapshot = BuildSnapshot(platform, window);
                var preview = GetWhatsAppPreviewText(candidate);
                var title = GetWhatsAppChatTitle(candidate);

                if (!string.IsNullOrWhiteSpace(preview))
                {
                    snapshot.LatestIncomingMessage = preview;
                }

                if (!string.IsNullOrWhiteSpace(title))
                {
                    snapshot.WindowTitle = title;
                }

                snapshot.Found = snapshot.ComposerFound || !string.IsNullOrWhiteSpace(snapshot.LatestIncomingMessage);
                snapshot.Message = "Detected an unread direct WhatsApp chat.";

                if (snapshot.Found)
                {
                    _lastWhatsAppDirectActivationUtc = DateTime.UtcNow;
                    return snapshot;
                }
            }

            return new ConversationSnapshot
            {
                Found = false,
                PlatformId = platform.Id,
                WindowTitle = SafeName(window),
                Message = "Unread direct WhatsApp chats were found, but the message preview could not be read."
            };
        }

        private ConversationSnapshot BuildSnapshot(MessagingPlatformDefinition platform, AutomationElement window)
        {
            var composer = FindComposer(window, platform);
            var candidates = FindMessageCandidates(platform, window);
            var latestMessage = candidates.LastOrDefault();
            var processName = SafeProcessName(window);

            return new ConversationSnapshot
            {
                Found = !string.IsNullOrWhiteSpace(latestMessage) || composer != null,
                PlatformId = platform.Id,
                WindowTitle = SafeName(window),
                ProcessName = processName,
                LatestIncomingMessage = latestMessage ?? string.Empty,
                ComposerFound = composer != null,
                DetectionMode = "active-window-scan",
                MatchedElementName = composer != null ? SafeName(composer) : string.Empty,
                DiagnosticInfo = BuildSnapshotDiagnostics(platform, window, candidates.Count, composer != null),
                Message = composer != null
                    ? "Chat window detected."
                    : "Detected a matching window but no chat composer was found."
            };
        }

        private ConversationSnapshot BuildBrowserConversationSnapshot(
            MessagingPlatformDefinition platform,
            AutomationElement window,
            bool autoSelectChat,
            string successMessage)
        {
            if (!autoSelectChat)
            {
                return BuildNotAutoSelectingSnapshot(
                    platform,
                    window,
                    "Chat auto-selection is disabled, so the currently open chat is used only.");
            }

            var snapshot = BuildSnapshot(platform, window);
            if (snapshot.Found && !string.IsNullOrWhiteSpace(snapshot.LatestIncomingMessage))
            {
                snapshot.Message = successMessage;
                return snapshot;
            }

            if (snapshot.ComposerFound)
            {
                snapshot.Found = false;
                snapshot.Message = "The chat is open, but no readable incoming message was detected yet.";
            }

            return snapshot;
        }

        private ConversationSnapshot BuildMessengerConversationSnapshot(
            MessagingPlatformDefinition platform,
            AutomationElement window,
            bool autoSelectChat)
        {
            var snapshot = BuildBrowserConversationSnapshot(
                platform,
                window,
                autoSelectChat,
                "Messenger or Facebook chat detected.");
            if (snapshot.Found)
            {
                return snapshot;
            }

            if (ContainsBlockedOverlay(window))
            {
                snapshot.Found = false;
                snapshot.DetectionMode = "share-overlay-blocked";
                snapshot.DiagnosticInfo = AppendDiagnostic(snapshot.DiagnosticInfo, "share overlay detected");
                snapshot.Message = "Facebook share dialog was detected and ignored. Switch back to the chat popup or disable auto-select.";
            }

            return snapshot;
        }

        private ConversationSnapshot BuildNotAutoSelectingSnapshot(
            MessagingPlatformDefinition platform,
            AutomationElement window,
            string message)
        {
            var snapshot = BuildSnapshot(platform, window);
            snapshot.Message = message;
            snapshot.DetectionMode = "manual-current-chat";
            snapshot.DiagnosticInfo = AppendDiagnostic(snapshot.DiagnosticInfo, "autoSelect=false");
            return snapshot;
        }

        private static List<string> FindMessageCandidates(
            MessagingPlatformDefinition platform,
            AutomationElement window)
        {
            var texts = window.FindAll(
                TreeScope.Descendants,
                new OrCondition(
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Text),
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Document),
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.ListItem),
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Custom),
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Edit)));

            var candidates = new List<string>();
            var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var windowTitle = NormalizeToken(SafeName(window));

            foreach (AutomationElement item in texts)
            {
                if (IsInsideBlockedOverlay(item))
                {
                    continue;
                }

                foreach (var token in SplitTokens(SafeName(item)))
                {
                    if (!LooksLikeMessageCandidate(token, platform, windowTitle))
                    {
                        continue;
                    }

                    if (seen.Add(token))
                    {
                        candidates.Add(token);
                    }
                }
            }

            return candidates;
        }

        private static bool LooksLikeMessageCandidate(
            string token,
            MessagingPlatformDefinition platform,
            string windowTitle)
        {
            var normalized = NormalizeToken(token);
            if (string.IsNullOrWhiteSpace(normalized))
            {
                return false;
            }

            if (normalized.Length < 2 || normalized.Length > 400)
            {
                return false;
            }

            if (normalized.Equals(windowTitle, StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            if (normalized.Equals("send", StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            if (IsUnreadToken(normalized) || IsLikelyTimeToken(normalized) || LooksLikeToolingLabel(normalized))
            {
                return false;
            }

            if (ContainsAny(
                normalized,
                "type a message",
                "write a message",
                "reply message",
                "reply privately",
                "message input",
                "press enter",
                "double tap",
                "new conversation",
                "new messages",
                "mark as read",
                "open navigation",
                "open menu",
                "create room",
                "voice clip",
                "record voice",
                "search input",
                "emoji picker",
                "choose sticker",
                "attach a file",
                "add reaction",
                "message actions",
                "share now",
                "share to",
                "send in messenger",
                "what's on your mind",
                "feed",
                "only me"))
            {
                return false;
            }

            if (!ContainsLetterOrDigit(normalized))
            {
                return false;
            }

            if (IsTelegramPlatform(platform) &&
                ContainsAny(normalized, "telegram", "unigram", "saved messages", "forwarded message"))
            {
                return false;
            }

            if (IsMessengerFamilyPlatform(platform) &&
                ContainsAny(normalized, "messenger", "facebook", "meta ai", "marketplace listing"))
            {
                return false;
            }

            if (IsWhatsAppPlatform(platform) &&
                ContainsAny(normalized, "whatsapp", "online", "last seen", "tap here", "click to react"))
            {
                return false;
            }

            return true;
        }

        private static AutomationElement[] FindWhatsAppUnreadChatCandidates(AutomationElement window)
        {
            var rows = window.FindAll(
                TreeScope.Descendants,
                new OrCondition(
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.ListItem),
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.DataItem),
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Custom)));

            var matches = new List<AutomationElement>();
            foreach (AutomationElement row in rows)
            {
                if (!HasUnreadMarker(row))
                {
                    continue;
                }

                var title = GetWhatsAppChatTitle(row);
                if (string.IsNullOrWhiteSpace(title))
                {
                    continue;
                }

                if (LooksLikeToolingLabel(title))
                {
                    continue;
                }

                matches.Add(row);
            }

            return matches.ToArray();
        }

        private static bool HasUnreadMarker(AutomationElement element)
        {
            foreach (var token in GetElementTokens(element))
            {
                if (IsUnreadToken(token))
                {
                    return true;
                }
            }

            return false;
        }

        private static string GetWhatsAppChatTitle(AutomationElement element)
        {
            foreach (var token in GetElementTokens(element))
            {
                if (IsUnreadToken(token) || IsLikelyTimeToken(token) || LooksLikeToolingLabel(token))
                {
                    continue;
                }

                return token;
            }

            return string.Empty;
        }

        private static string GetWhatsAppPreviewText(AutomationElement element)
        {
            var title = GetWhatsAppChatTitle(element);
            var tokens = GetElementTokens(element);

            for (var index = tokens.Count - 1; index >= 0; index--)
            {
                var token = tokens[index];
                if (token.Equals(title, StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                if (IsUnreadToken(token) || IsLikelyTimeToken(token) || LooksLikeToolingLabel(token))
                {
                    continue;
                }

                return token;
            }

            return string.Empty;
        }

        private static bool IsLikelyWhatsAppGroupRow(AutomationElement element)
        {
            var title = GetWhatsAppChatTitle(element);
            if (ContainsAny(title, "group", "community", "channel", "broadcast", "members", "participants"))
            {
                return true;
            }

            var preview = GetWhatsAppPreviewText(element);
            var colonIndex = preview.IndexOf(':');
            if (colonIndex > 0 && colonIndex <= 24)
            {
                return true;
            }

            return false;
        }

        private static bool TryActivateChat(AutomationElement element)
        {
            try
            {
                object selectionPattern;
                if (element.TryGetCurrentPattern(SelectionItemPattern.Pattern, out selectionPattern))
                {
                    ((SelectionItemPattern)selectionPattern).Select();
                    return true;
                }
            }
            catch
            {
            }

            if (TryInvoke(element))
            {
                return true;
            }

            try
            {
                element.SetFocus();
                SendKeys.SendWait("{ENTER}");
                return true;
            }
            catch
            {
                return false;
            }
        }

        private static AutomationElement FindComposer(AutomationElement window, MessagingPlatformDefinition platform)
        {
            var editors = window.FindAll(
                TreeScope.Descendants,
                new OrCondition(
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Edit),
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Document)));

            AutomationElement preferred = null;
            AutomationElement fallback = null;

            foreach (AutomationElement editor in editors)
            {
                if (IsInsideBlockedOverlay(editor))
                {
                    continue;
                }

                var name = SafeName(editor);
                if (name.IndexOf("search", StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    continue;
                }

                if (IsMessengerFamilyPlatform(platform) &&
                    ContainsAny(name, "share", "post", "what's on your mind"))
                {
                    continue;
                }

                fallback = editor;
                if (ContainsAny(name, "message", "reply", "write", "type", "chat", "textbox"))
                {
                    preferred = editor;
                }
            }

            return preferred ?? fallback;
        }

        private static AutomationElement FindSendButton(AutomationElement window, MessagingPlatformDefinition platform)
        {
            var controls = window.FindAll(
                TreeScope.Descendants,
                new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Button));

            foreach (AutomationElement control in controls)
            {
                if (IsInsideBlockedOverlay(control))
                {
                    continue;
                }

                var name = SafeName(control);
                if (IsMessengerFamilyPlatform(platform) &&
                    ContainsAny(name, "share now", "share", "send in messenger"))
                {
                    continue;
                }

                if (name.IndexOf("send", StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    return control;
                }
            }

            return null;
        }

        private static bool TrySetComposerText(AutomationElement composer, string text)
        {
            try
            {
                object valuePattern;
                if (composer.TryGetCurrentPattern(ValuePattern.Pattern, out valuePattern))
                {
                    ((ValuePattern)valuePattern).SetValue(text ?? string.Empty);
                    return true;
                }

                composer.SetFocus();
                SendKeys.SendWait("^a");
                SendKeys.SendWait("{BACKSPACE}");
                SendKeys.SendWait(text ?? string.Empty);
                return true;
            }
            catch
            {
                return false;
            }
        }

        private static bool TryInvoke(AutomationElement element)
        {
            try
            {
                object invokePattern;
                if (element.TryGetCurrentPattern(InvokePattern.Pattern, out invokePattern))
                {
                    ((InvokePattern)invokePattern).Invoke();
                    return true;
                }
            }
            catch
            {
                return false;
            }

            return false;
        }

        private static bool MatchesWindow(AutomationElement window, MessagingPlatformDefinition platform)
        {
            try
            {
                var processId = window.Current.ProcessId;
                var process = Process.GetProcessById(processId);
                var processMatch = platform.ProcessNames.Any(name =>
                    process.ProcessName.Equals(name, StringComparison.OrdinalIgnoreCase));

                if (!processMatch)
                {
                    return false;
                }

                var title = SafeName(window);
                if (platform.WindowTitleHints == null || platform.WindowTitleHints.Length == 0)
                {
                    return true;
                }

                return platform.WindowTitleHints.Any(hint =>
                    title.IndexOf(hint, StringComparison.OrdinalIgnoreCase) >= 0);
            }
            catch
            {
                return false;
            }
        }

        private bool HasRecentWhatsAppDirectActivation()
        {
            return DateTime.UtcNow - _lastWhatsAppDirectActivationUtc <= TimeSpan.FromMinutes(5);
        }

        private static bool IsWhatsAppPlatform(MessagingPlatformDefinition platform)
        {
            return platform != null &&
                   platform.Id.Equals("whatsapp", StringComparison.OrdinalIgnoreCase);
        }

        private static bool IsTelegramPlatform(MessagingPlatformDefinition platform)
        {
            return platform != null &&
                   platform.Id.Equals("telegram", StringComparison.OrdinalIgnoreCase);
        }

        private static bool IsMessengerFamilyPlatform(MessagingPlatformDefinition platform)
        {
            if (platform == null)
            {
                return false;
            }

            return platform.Id.Equals("messenger", StringComparison.OrdinalIgnoreCase) ||
                   platform.Id.Equals("facebook-messages", StringComparison.OrdinalIgnoreCase);
        }

        private static List<string> GetElementTokens(AutomationElement element)
        {
            var values = new List<string>();
            AddTokens(values, SafeName(element));

            var descendants = element.FindAll(
                TreeScope.Descendants,
                new OrCondition(
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Text),
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.ListItem),
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Custom),
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Button),
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Document),
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Edit)));

            foreach (AutomationElement descendant in descendants)
            {
                AddTokens(values, SafeName(descendant));
            }

            return values
                .Where(value => !string.IsNullOrWhiteSpace(value))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();
        }

        private static IEnumerable<string> SplitTokens(string rawText)
        {
            if (string.IsNullOrWhiteSpace(rawText))
            {
                return Enumerable.Empty<string>();
            }

            return rawText
                .Replace("\r", "\n")
                .Split(new[] { '\n' }, StringSplitOptions.RemoveEmptyEntries)
                .Select(part => NormalizeToken(part))
                .Where(part => !string.IsNullOrWhiteSpace(part));
        }

        private static void AddTokens(List<string> values, string rawText)
        {
            foreach (var token in SplitTokens(rawText))
            {
                if (token.Length >= 2)
                {
                    values.Add(token);
                }
            }
        }

        private static bool LooksLikeToolingLabel(string text)
        {
            return ContainsAny(
                text,
                "search",
                "filter",
                "new chat",
                "archived",
                "menu",
                "context",
                "communities",
                "status",
                "channels",
                "settings",
                "stories",
                "feeds",
                "marketplace",
                "notifications",
                "contacts",
                "calls",
                "people",
                "favorites",
                "saved messages",
                "communities and channels",
                "all chats");
        }

        private static bool IsUnreadToken(string text)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                return false;
            }

            int number;
            if (int.TryParse(text, out number))
            {
                return number > 0 && number < 1000;
            }

            return ContainsAny(text, "unread", "new message", "new messages");
        }

        private static bool IsLikelyTimeToken(string text)
        {
            if (string.IsNullOrWhiteSpace(text) || text.Length > 14)
            {
                return false;
            }

            if (ContainsAny(text, "yesterday", "today", "now"))
            {
                return true;
            }

            return text.Contains(":") &&
                   text.All(ch => char.IsDigit(ch) || ch == ':' || ch == '.' || ch == ' ' ||
                       ch == 'A' || ch == 'P' || ch == 'M' || ch == 'a' || ch == 'p' || ch == 'm');
        }

        private static bool ContainsAny(string text, params string[] values)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                return false;
            }

            foreach (var value in values)
            {
                if (text.IndexOf(value, StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    return true;
                }
            }

            return false;
        }

        private static string NormalizeToken(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return string.Empty;
            }

            return value
                .Replace('\r', ' ')
                .Replace('\n', ' ')
                .Replace('\t', ' ')
                .Trim();
        }

        private static bool ContainsLetterOrDigit(string value)
        {
            return !string.IsNullOrWhiteSpace(value) &&
                   value.Any(ch => char.IsLetterOrDigit(ch));
        }

        private static string BuildSnapshotDiagnostics(
            MessagingPlatformDefinition platform,
            AutomationElement window,
            int candidateCount,
            bool composerFound)
        {
            return string.Format(
                "platform={0}; candidates={1}; composer={2}; blockedOverlay={3}",
                platform != null ? platform.Id : "unknown",
                candidateCount,
                composerFound ? "yes" : "no",
                ContainsBlockedOverlay(window) ? "yes" : "no");
        }

        private static string AppendDiagnostic(string existing, string extra)
        {
            if (string.IsNullOrWhiteSpace(existing))
            {
                return extra ?? string.Empty;
            }

            if (string.IsNullOrWhiteSpace(extra))
            {
                return existing;
            }

            return existing + "; " + extra;
        }

        private static bool ContainsBlockedOverlay(AutomationElement window)
        {
            if (window == null)
            {
                return false;
            }

            foreach (var token in GetElementTokens(window))
            {
                if (ContainsAny(token, "share now", "share to", "send in messenger", "what's on your mind"))
                {
                    return true;
                }
            }

            return false;
        }

        private static bool IsInsideBlockedOverlay(AutomationElement element)
        {
            try
            {
                var current = element;
                for (var depth = 0; current != null && depth < 8; depth++)
                {
                    var name = SafeName(current);
                    if (ContainsAny(name, "share now", "share to", "send in messenger", "what's on your mind"))
                    {
                        return true;
                    }

                    current = TreeWalker.ControlViewWalker.GetParent(current);
                }
            }
            catch
            {
            }

            return false;
        }

        private static string SafeProcessName(AutomationElement window)
        {
            try
            {
                var process = Process.GetProcessById(window.Current.ProcessId);
                return process.ProcessName ?? string.Empty;
            }
            catch
            {
                return string.Empty;
            }
        }

        private static string SafeName(AutomationElement element)
        {
            try
            {
                return element.Current.Name ?? string.Empty;
            }
            catch
            {
                return string.Empty;
            }
        }
    }
}
