// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Windows.Automation;
using System.Windows.Forms;

namespace DeskCallAssistant
{
    public sealed class MessagingAutomationService
    {
        public MessagingPlatformDefinition[] GetSupportedPlatforms()
        {
            return new[]
            {
                new MessagingPlatformDefinition
                {
                    Id = "whatsapp",
                    DisplayName = "WhatsApp",
                    ProcessNames = new[] { "WhatsApp", "chrome", "msedge" },
                    WindowTitleHints = new[] { "WhatsApp" }
                },
                new MessagingPlatformDefinition
                {
                    Id = "telegram",
                    DisplayName = "Telegram",
                    ProcessNames = new[] { "Telegram", "chrome", "msedge" },
                    WindowTitleHints = new[] { "Telegram" }
                },
                new MessagingPlatformDefinition
                {
                    Id = "messenger",
                    DisplayName = "Messenger",
                    ProcessNames = new[] { "Messenger", "chrome", "msedge" },
                    WindowTitleHints = new[] { "Messenger", "messenger.com" }
                },
                new MessagingPlatformDefinition
                {
                    Id = "facebook-messages",
                    DisplayName = "Facebook Messages",
                    ProcessNames = new[] { "chrome", "msedge" },
                    WindowTitleHints = new[] { "Facebook", "Messages" }
                }
            };
        }

        public ConversationSnapshot DetectConversation(MessagingPlatformDefinition platform)
        {
            if (platform == null)
            {
                return new ConversationSnapshot
                {
                    Found = false,
                    Message = "Select a platform first."
                };
            }

            var desktop = AutomationElement.RootElement;
            var windows = desktop.FindAll(TreeScope.Children, Condition.TrueCondition);
            foreach (AutomationElement window in windows)
            {
                if (!MatchesWindow(window, platform))
                {
                    continue;
                }

                var snapshot = BuildSnapshot(platform, window);
                if (snapshot.Found)
                {
                    return snapshot;
                }
            }

            return new ConversationSnapshot
            {
                Found = false,
                PlatformId = platform.Id,
                Message = "No matching chat window was found for the selected platform."
            };
        }

        public ConversationSnapshot DraftReply(MessagingPlatformDefinition platform, string replyText)
        {
            var snapshot = DetectConversation(platform);
            if (!snapshot.Found)
            {
                return snapshot;
            }

            var window = FindBestWindow(platform);
            if (window == null)
            {
                snapshot.Message = "The chat window disappeared before the reply could be drafted.";
                snapshot.Found = false;
                return snapshot;
            }

            var composer = FindComposer(window);
            if (composer == null)
            {
                snapshot.Message = "The chat composer could not be found.";
                snapshot.Found = false;
                return snapshot;
            }

            if (TrySetComposerText(composer, replyText))
            {
                snapshot.Message = "Drafted the reply into the active chat composer.";
                return snapshot;
            }

            snapshot.Message = "Found the chat, but failed to draft the reply into the composer.";
            snapshot.Found = false;
            return snapshot;
        }

        public ConversationSnapshot SendReply(MessagingPlatformDefinition platform, string replyText)
        {
            var drafted = DraftReply(platform, replyText);
            if (!drafted.Found)
            {
                return drafted;
            }

            var window = FindBestWindow(platform);
            if (window == null)
            {
                drafted.Message = "The chat window disappeared before send could be attempted.";
                drafted.Found = false;
                return drafted;
            }

            var sendButton = FindSendButton(window);
            if (sendButton != null && TryInvoke(sendButton))
            {
                drafted.Message = "Sent the drafted reply.";
                return drafted;
            }

            try
            {
                window.SetFocus();
                SendKeys.SendWait("{ENTER}");
                drafted.Message = "Sent the drafted reply using the Enter key.";
                return drafted;
            }
            catch
            {
                drafted.Found = false;
                drafted.Message = "Failed to send the reply automatically.";
                return drafted;
            }
        }

        private AutomationElement FindBestWindow(MessagingPlatformDefinition platform)
        {
            var desktop = AutomationElement.RootElement;
            var windows = desktop.FindAll(TreeScope.Children, Condition.TrueCondition);
            foreach (AutomationElement window in windows)
            {
                if (MatchesWindow(window, platform))
                {
                    return window;
                }
            }

            return null;
        }

        private ConversationSnapshot BuildSnapshot(MessagingPlatformDefinition platform, AutomationElement window)
        {
            var texts = window.FindAll(
                TreeScope.Descendants,
                new OrCondition(
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Text),
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Document),
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.ListItem)));

            var candidates = new List<string>();
            foreach (AutomationElement item in texts)
            {
                var name = SafeName(item);
                if (string.IsNullOrWhiteSpace(name))
                {
                    continue;
                }

                if (name.Length < 2)
                {
                    continue;
                }

                if (name.Equals("Send", StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                candidates.Add(name.Trim());
            }

            var latestMessage = candidates.LastOrDefault();
            var composer = FindComposer(window);

            return new ConversationSnapshot
            {
                Found = !string.IsNullOrWhiteSpace(latestMessage) || composer != null,
                PlatformId = platform.Id,
                WindowTitle = SafeName(window),
                LatestIncomingMessage = latestMessage ?? string.Empty,
                ComposerFound = composer != null,
                Message = composer != null
                    ? "Chat window detected."
                    : "Detected a matching window but no chat composer was found."
            };
        }

        private static AutomationElement FindComposer(AutomationElement window)
        {
            var editors = window.FindAll(
                TreeScope.Descendants,
                new OrCondition(
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Edit),
                    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Document)));

            foreach (AutomationElement editor in editors)
            {
                var name = SafeName(editor);
                if (name.IndexOf("search", StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    continue;
                }

                return editor;
            }

            return null;
        }

        private static AutomationElement FindSendButton(AutomationElement window)
        {
            var controls = window.FindAll(
                TreeScope.Descendants,
                new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Button));

            foreach (AutomationElement control in controls)
            {
                var name = SafeName(control);
                if (name.IndexOf("send", StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    return control;
                }
            }

            return null;
        }

        private static bool TrySetComposerText(AutomationElement composer, string text)
        {
            try
            {
                object valuePattern;
                if (composer.TryGetCurrentPattern(ValuePattern.Pattern, out valuePattern))
                {
                    ((ValuePattern)valuePattern).SetValue(text ?? string.Empty);
                    return true;
                }

                composer.SetFocus();
                SendKeys.SendWait("^a");
                SendKeys.SendWait(text ?? string.Empty);
                return true;
            }
            catch
            {
                return false;
            }
        }

        private static bool TryInvoke(AutomationElement element)
        {
            try
            {
                object invokePattern;
                if (element.TryGetCurrentPattern(InvokePattern.Pattern, out invokePattern))
                {
                    ((InvokePattern)invokePattern).Invoke();
                    return true;
                }
            }
            catch
            {
                return false;
            }

            return false;
        }

        private static bool MatchesWindow(AutomationElement window, MessagingPlatformDefinition platform)
        {
            try
            {
                var processId = window.Current.ProcessId;
                var process = Process.GetProcessById(processId);
                var processMatch = platform.ProcessNames.Any(name =>
                    process.ProcessName.Equals(name, StringComparison.OrdinalIgnoreCase));

                if (!processMatch)
                {
                    return false;
                }

                var title = SafeName(window);
                if (platform.WindowTitleHints == null || platform.WindowTitleHints.Length == 0)
                {
                    return true;
                }

                return platform.WindowTitleHints.Any(hint =>
                    title.IndexOf(hint, StringComparison.OrdinalIgnoreCase) >= 0);
            }
            catch
            {
                return false;
            }
        }

        private static string SafeName(AutomationElement element)
        {
            try
            {
                return element.Current.Name ?? string.Empty;
            }
            catch
            {
                return string.Empty;
            }
        }
    }
}
