// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

namespace DeskCallAssistant
{
    public sealed class ReplySuggestionResult
    {
        public string ReplyText { get; set; }

        public int Score { get; set; }

        public bool UsedFallback { get; set; }

        public string Language { get; set; }

        public string PlatformId { get; set; }
    }
}
