// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Speech.Synthesis;

namespace DeskCallAssistant
{
    public sealed class SpeechService : IDisposable
    {
        private readonly SpeechSynthesizer _synthesizer = new SpeechSynthesizer();

        public string[] GetInstalledVoices()
        {
            return _synthesizer.GetInstalledVoices()
                .Select(voice => voice.VoiceInfo.Name)
                .OrderBy(name => name)
                .ToArray();
        }

        public void Configure(string voiceName, int rate, int volume)
        {
            if (!string.IsNullOrWhiteSpace(voiceName))
            {
                _synthesizer.SelectVoice(voiceName);
            }

            _synthesizer.Rate = Math.Max(-10, Math.Min(10, rate));
            _synthesizer.Volume = Math.Max(0, Math.Min(100, volume));
        }

        public void SpeakAsync(string text)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                return;
            }

            _synthesizer.SpeakAsyncCancelAll();
            _synthesizer.SetOutputToDefaultAudioDevice();
            _synthesizer.SpeakAsync(text.Trim());
        }

        public void Stop()
        {
            _synthesizer.SpeakAsyncCancelAll();
        }

        public void Dispose()
        {
            _synthesizer.Dispose();
        }
    }
}
