// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

using Microsoft.Win32;

namespace DeskCallAssistant
{
    public sealed class StartupRegistrationService
    {
        private const string RunKeyPath = @"Software\Microsoft\Windows\CurrentVersion\Run";
        private const string AppName = "DeskCallAssistant";

        public void SetEnabled(bool enabled, string executablePath)
        {
            using (var key = Registry.CurrentUser.OpenSubKey(RunKeyPath, true) ??
                             Registry.CurrentUser.CreateSubKey(RunKeyPath))
            {
                if (key == null)
                {
                    return;
                }

                if (enabled)
                {
                    key.SetValue(AppName, "\"" + executablePath + "\"");
                }
                else
                {
                    key.DeleteValue(AppName, false);
                }
            }
        }

        public bool IsEnabled()
        {
            using (var key = Registry.CurrentUser.OpenSubKey(RunKeyPath, false))
            {
                if (key == null)
                {
                    return false;
                }

                return key.GetValue(AppName) != null;
            }
        }
    }
}
