// AI-generated source notice:
// This file was generated by an AI coding assistant.
// The human requester should not be represented as the original author of this implementation.

using System;
using System.IO;
using System.Linq;

namespace DeskCallAssistant
{
    public sealed class StorageLocationService
    {
        private const long MinimumFreeBytes = 200L * 1024L * 1024L * 1024L;

        public string FindExternalStorageRoot()
        {
            var drives = DriveInfo.GetDrives()
                .Where(drive => drive.IsReady)
                .Where(drive => drive.DriveType == DriveType.Fixed || drive.DriveType == DriveType.Removable)
                .Where(drive => !drive.Name.StartsWith("C", StringComparison.OrdinalIgnoreCase))
                .Where(drive => drive.AvailableFreeSpace >= MinimumFreeBytes)
                .OrderByDescending(drive => drive.AvailableFreeSpace)
                .ToArray();

            var selected = drives.FirstOrDefault();
            return selected != null ? selected.RootDirectory.FullName : string.Empty;
        }

        public string EnsureAppDataPath(string relativeFolder)
        {
            var root = FindExternalStorageRoot();
            if (string.IsNullOrWhiteSpace(root))
            {
                return string.Empty;
            }

            var path = Path.Combine(root, "DeskCallAssistantData", relativeFolder ?? string.Empty);
            Directory.CreateDirectory(path);
            return path;
        }

        public string BuildStatusMessage(string path)
        {
            if (string.IsNullOrWhiteSpace(path))
            {
                return "No external drive with at least 200 GB free space is currently available.";
            }

            return string.Format(
                "External memory path: {0}{1}No credentials are stored in code or persisted by the Fiverr helper.",
                path,
                Environment.NewLine);
        }
    }
}
